/* ffi-share.js - Fight for Illinois share cards (hosted copy).

   This is the same engine the pages carry inline (_ffi-cards.js in the site
   project), plus the card logo, published for any page that still loads the
   hosted files. Self-contained and self-guarding: if a page already installed
   the engine inline, this copy sees window.FFI_CARDS and does nothing.

   Defines:
     window.FFI_CARDS    { draw, show, shareNow, payload, wire }
     window.FFI_makeCard(payload, cb)   paints a 1080x1920 PNG blob
     window.ffiShareCard(blob, opts)    preview overlay + share/save handoff
     window.FFI_SHARE_SCAN()            no-op, kept for older pages
     window.FFI_CARD_LOGO               700px JPEG data URI

   Card type comes from the payload: pie, cols, delta, bars, tbl, rows, else a
   big-number card. One delegated click listener handles every .ffi-share
   button, including buttons added to the page later.

   Upload alongside ffi-sharebar.js. Cache-bust with ?v=<hour>. */

(function(){
  if (window.FFI_CARD_LOGO) return;
  window.FFI_CARD_LOGO = [
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AA",
  "BAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABR",
  "yVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHA",
  "EJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXB",
  "hcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAAS",
  "QBuAGMALgAgADIAMAAxADb/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBI",
  "UFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAD3ArwDA",
  "SIAAhEBAxEB/8QAHgABAQEBAQACAwEAAAAAAAAAAAkIBwYFCgECBAP/xABhEAAABQICBAYKCg0KAwgCAwAAAQIDBAUGBxEICRIhGTE4QVF1EyI",
  "3VWFxlbO00hQyV3R2gZSxstQVIzVCUlZyc5GSocLTFhcYMzZUYoKT0SRjwTQ5REVTg4WiJbVko+H/xAAcAQACAwADAQAAAAAAAAAAAAAABQMEB",
  "gECBwj/xAA9EQACAgEBAwgIAwcFAQEAAAAAAQIDBBEFITESFDIzQVFxgQYTNFJhkaGxBxUiQnKSwcLR8BYXIzVi4UP/2gAMAwEAAhEDEQA/AKp",
  "gMnae2lbd+i9Dsp21INGmqrTkxMgquw66SSaJk07Gw4jL+sVnnnzcQyFws2MPeKzPkEr6yLteHbbFTjwK08iEJcllbgEkeFmxh7xWZ8glfWQ4W",
  "bGHvFZnyCV9ZEv5ff8AA6c6rK3AJI8LNjD3isz5BK+shws2MPeKzPkEr6yD8vv+Ac6rK3AJI8LNjD3isz5BK+shws2MPeKzPkEr6yD8vv8AgHO",
  "qytwCSPCzYw94rM+QSvrIoRgNjJW8T9GKlYiVWPBZrkqnS5a2Yja0xyW046lJElS1KyybTn23TxCC3FspSc+0khfCx6ROzAJI8LNjD3isz5BK+",
  "shws2MPeKzPkEr6yJ/y+/4EfOqytwCSPCzYw94rM+QSvrI7ZoeafmImP+N9Ps+4qVbcWlyIsh9blNivtvEpCNpORrfWWWfHuHSeFdCLk+CO0cm",
  "uTSRQIAAUC0AAc0xm0jMP8BKUqZeFfYhPmk1M09n7bLfPmJDSd+/pPJPSZDtGLk9IrVnDaitWdLATHxO1t9alrej2DaEWnsnmSJtcWbzmXT2JB",
  "kkj8alF4xmq6NOXHO7XnFysRKnEQozMmqYluGlJdBdiSk8vGZhjDZ90t73FSWXWuG8uaAgGrSRxVW5tqxEuU19P2Td9YfPUHTJxstt1K4WJVdV",
  "lxIlvlJR+q6Si/YJXs2fZJEfPI9xd4BJvDnWu4k292Ji7aPSbsjJyJchts4ck+k80fa/0IIbWwI09MLccjZgt1M7YuFZkn7E1kybNZ/8ALd9ov",
  "xZkr/CKdmJdVva3fAsQvrnuTNHAPwR5lmXEPyKZYACU1261HFug3XWqZHolnqjwpr0ZtTkGSajShxSSMzKSW/IugfFcLNjD3isz5BK+shisC57",
  "9xT51WVuASR4WbGHvFZnyCV9ZHRNHnWSYn4sY2WfaFYo9qsUyrzkxpDkOHIQ8lJkZ5pNUhREe7nIxxLBuim3puOVk1t6IpUAAF5bADkWlhi3Wc",
  "DMBblvWgMQpNWppxiZaqDa1sn2SQ22raSlSTPtVnlkot+Qndws2MPeKzPkEr6yLdOLZdHlQ4EFl8K3pIrcAkjws2MPeKzPkEr6yHCzYw94rM+Q",
  "SvrIn/L7/AIEXOqytwDKGgVpV3dpQU6837rg0eEujOxERypDDrRKJ0nTVt7bi8/6ssssucZ3xw1mGKWG2L132tS6Naj1OpFSehsOSoUlTqkJVk",
  "RqNMgiM/ERCGOLZKbrXFEjvgoqb4MpuAkjws2MPeKzPkEr6yHCzYw94rM+QSvrIm/L7/gR86rK3AJI8LNjD3isz5BK+shws2MPeKzPkEr6yD8v",
  "v+Ac6rK3AJI8LNjD3isz5BK+shws2MPeKzPkEr6yD8vv+Ac6rK3AJI8LNjD3isz5BK+shws2MPeKzPkEr6yD8vv8AgHOqytwCamj1rJMT8V8ar",
  "QtGr0e1WKZV5yYz7kOHIQ8lJkZ5pNUhREe7nIxSsVLqZ0NRmT12RsWsQAAICUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzt+3",
  "pFw+tmTW5kaRKjMGklojJJSiIzyz3mW4eiH88+BHqsJ+HLZRIivoNtxpws0qSZZGRiG6Nkq5Kp6S0ej46Ps3E9Eqo2xldHlQTWqT0bXbvOFf0y",
  "bS72VT9RHrAemTaXeyqfqI9YZ2xqwvfwtvF6ClK1UuRm9CfVv2m8/amfSniP4j5xz8eE5PpZtzDulj3OKlF6P8ASj6OxPQr0ezqIZNCk4SWq/U",
  "/88TZH9Mq0u9dU/UR6wf0yrS711T9RHrDG4Ct/rXa/vR/hRc/2/2H7kv4mbI/plWl3rqn6iPWD+mVaXeuqfqI9YY3AH+tdr+9H+FB/t/sP3Jfx",
  "M2R/TKtLvXVP1EesH9Mq0u9dU/UR6wxuAP9a7X96P8ACg/2/wBh+5L+JmyP6ZVpd66p+oj1g/plWl3rqn6iPWGNwB/rXa/vR/hQf7f7D9yX8TN",
  "kf0yrS711T9RHrDuNFqzFepEOoxtr2PLZS83tFkeyosyzExhRDBSpIq2FNsSEGRl7CQ2eXMpPamX6SMbn0U9IMza2RZTlNPRarRaduj+5516ae",
  "jODsTGqvwotcqWj1evZqvsz2wAA9MPIyc+uF+5uFf56p/RiiagpXrhfubhX+eqf0YomoNTg+zx8/uI8nrWAABfKwAAAAAAAAFotD/kD271LUvP",
  "SRF0Wi0P+QPbvUtS89JCvaHVx8S7idN+BF0AANCkBqzVlcq+jdXzPNjKY1ZqyuVfRur5nmxXyOpn4Mlp6yPiWXABlXT60qz0fcPUUagvkV7V9C",
  "m4i0nvhM8S5Bl0/ep8J5/e5Hk665WyUI8WPZyUIuTPG6bGsAYwcflWTYK2p95pzRNqCyJbFNPL2pEeZLd8B7k8+Z7hKu5bnq95VuXWK7UpNWqk",
  "tZuPy5bpuOLUfSZ/NxEP4JMl6bJdkSHVvvurNxx1xRqUtRnmZmZ8ZmfOP8xq6MeFEdI8e8R22yterAAAskIAAAAH5So0qIyMyMt5GXMPwBEZnk",
  "W8wAbp0D9NDEan3tb2GtQhzL7ok50o8dG1tTICOM1pWr2zaCIzNKz3ER5GWREKtDHerw0T04LWOV53FGyvOvspUltxOSoEQ8jS1lxktXtlf5S5",
  "jz2IMplyrla/Vr/6PMeMow/Wz672I/dDujrWV55Q86PRYj90O6OtZXnlDzo1MeCEj4gdr0K+VVhp1sj6KhxQdr0K+VVhp1sj6Kh0t6uXgztX01",
  "4l2AABjDRGbNYvyPr68cH01gRPFsNYvyPr68cH01gRPGj2d1L8f5IUZnWLwAAAalEpfqfPuLij74p30ZAxRpY8pXErryT9MxtfU+fcXFH3xTvo",
  "yBijSx5SuJXXkn6ZhZV7XZ4L+Rcs6iBycAAMymAAAAAAAAAAAAdq0LeVRhr1qj6KhdkQm0LeVRhr1qj6KhdkZ7aXWR8Bth9B+IAACgvgAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHicXMMYeKdpvUx8yZmN5uxJOWfYnMt2fgPiMYAuGgTrWrcyk1Jk482K4bbjZ8x8xl0kZZ",
  "GR9BimoyZpo0WJHrdv1RtKUS5LLjLplxrJBkaTPxbRl+geX+m2yKrcb8xhunDRP4pvT5rX5eR7B+H227qcv8AKp7656tf+Wlq/JpfPf3mbAAB4",
  "efRAAAAAAAAAAAAAGr9Di/PZNMqNpyXM3IyjlxSM/vFGRLSXiVkf+YxlAeqwtu92xb+o1ZQs0tsPkl4vwmldqsv1TP48hoNg7RezNoV36/p10l",
  "4Pj8uPkZj0k2Wtr7Ltxkv1aax/eW9fPh5lHAH6MuofaQ62olIWklJUXOR8Q/cfUHE+P2tNzJz64X7m4V/nqn9GKJqCleuF+5uFf56p/Riiag1O",
  "D7PHz+4iyetYAAF8rGn8G9XliTjhhzSb0oFVtmNSql2TsLVQlvoeLYcU2e0SWFEW9B5ZGe7Ie14JrGHv5Zny+V9WG39XfyQbE8Uz0x4aQGdtzr",
  "oWSiuxjaGNXKKbJIcE1jD38sz5fK+rBwTWMPfyzPl8r6sK3gI/wAwv+B35rWSQ4JrGHv5Zny+V9WG/sHcLqtgtomR7Lrj0SRVaVSJ6H3YC1LZU",
  "a1POFsmpKTPcsuMi35juI+Bv7+wlx9WyfNKEVmVZfpGfeSQphXq4n12gABqxEBqzVlcq+jdXzPNjKY1ZqyuVfRur5nmxXyOpn4Mlp6yPiWRmzG",
  "afDflSFk0ww2p1xauJKSLMz/QQgppNYzTceMaLiuuS6o4jr5x6eyZ9qzFb7VpJeMi2j6VKUfOK4aeWIzuGmi5ecyK52OfUmUUiOeeRkchRIcMv",
  "CTRuGXhIhD0LNm17nY/AuZk96gAAA7FwHa9HzRCxD0jpJu27TkQqE2rZerlRUbcZBlxpTuNTivAkjy5zIfrojaP0jSNxlptur22qHGSc2rSEnk",
  "bcZBlmkj/AAlqNKC/KM+Yxce27bpln0GDRaNBZptLgspYjxY6CShtCSyIiIgsy8v1H6IcS5RR6z9UuBPej6oCN7E//K4kOlKy/wDB0wtj/wCzm",
  "Y8ViHqlrzo0B+VaF1U643GyNSYMxs4jrngSrNSMz/xGkvCKoAFKzr09dS+8aprTQ+u5fOH1yYaV56i3TRZlCqjXto8xo0GZdKT4lF4SMyMa+1b",
  "+icrE27EYjXNDSq1aI+XsGO+nNM6WW8jyPjQ3uM89xqMi35HlR/G/AGzdIG1F0S7aYiSSe2jTmiJMmIv8JteWZeEuI+cjHqbHsqjYc2lSrat+G",
  "iBR6YwmPHYRzJIuMz51GeZmZ7zMzM+MWbc9zq5KWjZDDF5M9W9UfOgABOMD672I/dDujrWV55Q86PRYj90O6OtZXnlDzo20eCM2+IHa9CvlVYa",
  "dbI+iocUHTdGe+KRhtj1ZNz159cWj0uoJkSnkNqcUhBEZZklJGZ8fMOtibhJLuZ2g9JJsvsAy3wluAn4zzvJEn1A4S3AT8Z53kiT6gyfN7vcfy",
  "Hvra/eR8jrF+R9fXjg+msCJ4ptpkacGEeMOjpdVpWvXZc2tzzi9gZdpz7SVbElpxWalJIi7VCj3mJkh9gQlCpqS03/2FeVJSmnF67gAAGRTKX6",
  "nz7i4o++Kd9GQPgcbtWbiZiTi7d1002uWuxAq9RemMNypMhLqULVmRKImTIj8RmPntT59xcUffFO+jIFFBnL750ZM3D4fZDequNlMVIktwS2LP",
  "4xWh8rk/Vw4JbFn8YrQ+Vyfq4rSAj5/f3o7c1rPrrXvacuwr0r9sz3GXp1FqEimyHI5mbanGXFNqNJmRGaTNJ5ZkR5cxD4UdG0kuUVin8Kqr6W",
  "6OcjSwesU2J5LRtAehw8sidiVfNCtWmusMVCsS24TDkpRpaStZ5EajIjMi38xGPPDrGidyl8M+vonnCHE24xbRzFaySZoLglsWfxitD5XJ+rhw",
  "S2LP4xWh8rk/VxWkBm+f396G/NaybOj5q2cScKMabRu+rVu2ZFOpE1Ml9qJJfU6pJEZZJJTJEZ7+cyFJgAVbrp3tSmT11xrWkQAAICUAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/BnkWZjBukZiL/OBiHIKOojplMI4cbLiXkZ7a/jVn8RENTaQeI6cPMP5amHSRVZ5HFiFn",
  "2xGZdssvySPPxmQwOZmZmZnmZ85jyD062puhs6t/wDqX8l/P5Huf4c7H3z2rav/ADD+p/y+Z+AAB48e6gAAAAAAAAAAAAAAAG69Ga//AOWuHEa",
  "NIcJdRpOUR7M96kEX2tX6uReNJjrYwpov3TIt7FenRUOGUWpkqK83nuVuM0n4yURfpPpG6x9Ieiu0ntHZsXPpQ/S/jolo/lp5nyj6Z7Kjsra01",
  "X0LP1r4at6r56+WhOfXC/c3Cv8APVP6MUTUFK9cL9zcK/z1T+jFE1B6zg+zx8/ueU5PWsAAC+VjteHmmTi1hXaEC2LZug6dRYO32CMUVpextLN",
  "at6kmZ5qUZ/GPR8IXjx+OqvkTHqDOICF01t6uK+RIrJrcmzR3CF48fjqr5Ex6gcIXjx+OqvkTHqDOIDj1FXur5B62fvM2no66cOMt847WHb9Zu",
  "1Uuk1KsRospj2IynsjalkSk5knMsy6BVK/v7CXH1bJ80oQ10SOU7hf8IIfnCFyr+/sJcfVsnzSgkzoRhZFRWgyxZOUHqz67QAA0QpA1ZqyuVfR",
  "ur5nmxlMas1ZXKvo3V8zzYr5HUz8GS09ZHxNXa22sLiYL2pTiVkiZWttRdOwyvL6QlKKh63oj/m9w/P737KP+aIS8FfAX/AvMlyutYAADAqlRN",
  "UXZrMbD29rqU2RyJlSRTUuZbyQ00lwy/S8X6Bv8Y21U5tnoyTNj2xXDL2/yuxMf9MhskZLLet8tR9QtK4kXaxrEMdotWmsN3e2ltt9aEl9j2Nx",
  "EoyL7wfycIvjz+ODfk9j1Bni4Pu9UvfLv0zH8A0qoq06K+Qm9bZ7zNLcIvjz+ODfk9j1A4RfHn8cG/J7HqDNIDn1FXur5HHrbPeZpbhF8efxwb",
  "8nseoK1aPF11O+sC7EuGtPlKq1To8aXKeJBJ23FtkajyLcW8+YfX/F6dErkx4X/AAeh+aSFW0K4QhFxSW8vYk5Sk+U9SHGI/dDujrWV55Q86PR",
  "Yj90O6OtZXnlDzodR4IXPiAAB2OAAAAAAAAAAAACl+p8+4uKPvinfRkCignXqfPuLij74p30ZAooMpm+0S/zsHmP1SAAApFkgFpJcorFP4VVX0",
  "t0c5HRtJLlFYp/Cqq+lujnI2lfQXgZyXSYHWNE7lL4Z9fRPOEOTjrGidyl8M+vonnCBb0JeDOYdJF6wABizRAAAAAcG0qdLSkaK0O3JFVoM2uJ",
  "rTj7baYbqEG32ImzPPa48+yF+gd5E7NcH9w8LvfNR+jHFrGhGy2MJcGQ3ScK3JHy3C9Wh+IFb+VshwvVofiBW/lbIlyAfcwo7vqKudW95Ubher",
  "Q/ECt/K2Q4Xq0PxArfytkS5AHMKO76hzq3vLe6K+mRRtKidcMalW9OoaqM2y44qY8hZOE4ayIi2eLLYP9I0MJm6n7+0GJnvWD9N4dQ1humdKwj",
  "h/wA3tlTEs3ZOYJdQqDR5rpzCuJKeh1Zb8z9qk8+M0mSe3G1yHVUhhC7Sr1kzsuPWm3hjo/yXKbVqmusXChOZ0ekkTryN27sisyS3n0KPPeR5Z",
  "DI13a3ytvPOJtfD2nxGiV2jtXnLfUouk0NkjI/8xie0mS9NkuyJDq333Vm4464o1KWozzMzM+MzPnH+YbV4FMF+pasoTyrJPduKCWvre7mjvJK",
  "48PqTPaMyzVS5rsVSS5zyWTmfizIarwJ0/MLscahHpDc162Lgf3NU6s7LZPK/BbdI9hR9CcyM+YjEUB+ULU2tK0KNK0nmSknkZH0jmzApmv0rR",
  "hHKsi9+8+yEPAY84vQ8BsKK5fU+nv1SJSuwbcSMskuOdlfbZLIz3bjcI/iGLdXXprT7lnRMK76mrmTTQaaJVpC83HNks/Yzhn7Y8s9lXHuyPmG",
  "gNYryN8Qf/j//ANhGCR0Ou+NU+1r5DL1qnW5xOKcL1Z34g1z5UyHC82b+INd+VMiXAB5zCju+os51b3lSU63mzM99hV0i8Eln/ceotTWs4T1t9",
  "DVWplft4lKJPZHo6H0J8J9jUZ5fEJHAOHgUPs+pysq1dp9hjDrFS0cWqGmr2hcEGvwDy2lxHSNTZ8eytB9shXgURGPVj692E+Lt0YK3jDuW1ak",
  "5AnR1pNbZGZtSEEe9t1PEpJlmWXh3ZHvFydHrGqm4/wCFNGvKnNlGVLQbcqJtbRxpCdzjefORHvI+cjIJ8rEePvT1QwpvVu58TpAAAoFoAAAA8",
  "biBi3bOGjLZ1qcSJLhbTcRlO26sunZLiLwnkQ49X9NGmNR3E0agSZEjIyQ5McJCCPmMyTmZ+Ld4xn7GGTUJWJ9yKqalqlpmuIyWftUkeSCLwbO",
  "WXgHjR4TtT0y2i8iyrG0rim1w1e7dv17fLcfR2x/QLZaxq7svWyUkm9+kd+/dpo9PPeejvq/6ziLW1VStSezPZbLbaC2W2k/goTzF+3pHnAAed",
  "W22Xzdlsm5Pi3xPVKaa8euNVMVGMdyS3JAAAREwAAAAAAAAAAAAAAAB7vAvuu2r79T/ANRQsT1wJLPF61S//mp+YxQoe4+gPsN37/8AJHzt+JX",
  "/AGFH7n9TJz64X7m4V/nqn9GKJqCleuF+5uFf56p/Riiag94wfZ4+f3PBMnrWAABfKwAU60O9B/CPF3R2tS67moUqZW55SfZDzdQeaSrYkOIT2",
  "qVERdqkuIdn4NbAX8WJvlWR64Wzz6oScWnuLccWckmtCLwC0PBrYC/ixN8qyPXDg1sBfxYm+VZHrjr+Y09zO3NLPgS50SOU7hf8IIfnCFyr+/s",
  "JcfVsnzShxSzNATBiwLspNyUW3pcerUqSiXFdXUn1khxB5pM0mrI95cRjtd/f2EuPq2T5pQWZV8b5xcewu0VSqi1I+u0AANOJQNWasrlX0bq+Z",
  "5sZTGrNWVyr6N1fM82K+R1M/BktPWR8TWutooi5uBtt1Ik5pg1tKVH0dkaWX7ok8LqaaeGi8VtGi9qNHRtz2In2SiERZmbsdRO7JeFSUKR/mEK",
  "xT2dLWrk9zLGXHSzXvAAAaFIqLqirvak4eXva5rLs8Opt1FKM95pdaSgz/SyX6Rv4Qs0PNIR3Ryxmp9efNS7fmJODV2Elmao6jLtyL8JCiSouk",
  "iMucXFolbgXJSIdVpctmfTpjKX48mOsltutqLNKkmW4yMjGZz6nC3ldjHOLNShye1EGq5o84pO1qoLRhzdS0KkOKSpNGkGRkaj3+0Hnblwgvqz",
  "KWqpV+za9RKclZIOXUKa8w0Sj4i2lJIszH2FRkrWgclOodawvpmLdWfKc4w5PEr2YqjFy1I4gAB2LgL06JXJjwv8Ag9D80kQWF6dErkx4X/B6H",
  "5pIT7S6EfEv4fSZDjEfuh3R1rK88oedHosR+6HdHWsrzyh50No8EUXxAAOy6G8KPUtKDDiNLjtSoztVQlxl5BLQstlW4yPcYJS5MXLuCK5TSON",
  "APsQfzcWl+K9F8ns+qH83FpfivRfJ7PqhP+Zr3PqMOZv3j674Cy2sGsq3aRok3vLg0GmQpTZwth+PDbbWnOYyR5KJJGW4zIRpDDHvWRDlpaFS2",
  "r1UuTqAABaISl+p8+4uKPvinfRkCignXqfPuLij74p30ZAooMpm+0S/zsHmP1SAAApFkgFpJcorFP4VVX0t0c5HRtJLlFYp/Cqq+lujnI2lfQX",
  "gZyXSYHWNE7lL4Z9fRPOEOTjrGidyl8M+vonnCBb0JeDOYdJF6wABizRAAAAATs1wf3Dwu981H6McUTE7NcH9w8LvfNR+jHF3C9oj/nYVsnqmT",
  "PHb9D7AWlaR2MCbQrFSmUuGdPfmeyIJINzaQaci7YjLI9ocQHQMEMbrj0f73K6rWKGdUKM5FynMm63sLy2u1JRb+1LnGnsUnBqHESwaUlyuBRL",
  "gisP/AMdrl/Vj+oHBFYf/AI7XL+rH9QZv4VHGv/07a8mr/ihwqONf/p215NX/ABQp9Vm+9/nyL/LxvdN14HaL1p6FFBvm6INfqdUiOU45Uw6iT",
  "ZE03HS44Zp2ElzGfH0COeIV7VDEe+K5dFUcU7Pq0tyW6ajzyNR5knxEWRF4CIUxvHHy5MWdWddd6144rdbqO3T3Dgtm032M5yGTIkmZ8aDMj3i",
  "Vonw4y1nOx6y10+RHkNaRjHhxAoVolatWlYhWFTryxInT2Gqq2UiDRoBkyomFFmhxxwyM81EeZJIiyLI8zzyLCuHdAbuvEC2aI7n2KpVOLDXl0",
  "OOpQf0h9h6NGahRmo7DaWWGkE222gskoSRZERFzERDrn3yqSjB6NnOLVGbbl2E49JnVf0e37HqFx4XzJ651NaOQ9Rag4T3shpJZr7EsiIyWRby",
  "SeZHlluPLObxkaTMjLIy4yMfZAWhLiTSoiUlRZGR8RkPr8Y7261aONl/URhOxHp9enRmk9CEPrJP7CIcYF87dYzeuhzlVRhpKJ5KiVqdblYg1W",
  "mSnIVRgvokxpLKtlbTiFEpKiPmMjIjFcdKzENvFfVwVe7mySlVWgUqQ4hHElw58YlpLwEolEJAihdGrLlW1Q1xNOq2jgzW4qTP8H7LR1l+jby+",
  "ITZUE5Vz7pIiolopx+DJ6D1OFNsxL0xQs+3p6nEwatWIcB9TR5LJt19CFbJ8x5KPIeWHuMC6jFpGNuH06dJZhQYtw099+TIcJttptMls1LWo8i",
  "SkiIzMz3ERC9LXkvQrR4rUpxM1UWEr8VaGKrccZ4y7V32U2rZ+I0bxOPSYwEqOjhixULPnSPZ0dLaJcCds7HsmMvMkLNPMZGlSTLpSeW4Whk6T",
  "+D0Rhx5eKlmKQhJqMmq9FcUeXQlKzMz8BEJI6dePdI0hMdXa1b205QabBapcOStJoOSlC1uKc2T3kRqdUREe/JJHuzyCfCsvlNqeunxGGTCqMd",
  "Y8TPApjqgLqkyKDiRbjizOJEkQp7CM9yVupdQ5+kmWxM4U91Q1lSafZuIF1PINMapzIsCOZl7bsCXFLMvBm+kvGkxbztPUS1+H3IMbX1q0KDAA",
  "DLDsAA/R11DLa3HFEhtBGpSlHkREXGZgDiY50xbdYpl+0+qMpJC6lFzeIvvloPZ2v1dkviHAh0nH7EdOJGIEmVFVtUuGn2LE/xJL2y/8AMrM/F",
  "kObD5c27dTkbTvtx+i5Pz735vVn2L6OY9+LsjGpyemorX4dy8lovIAABEaMAAAAAAAAAAAAAAAAAAAA95gT3X7V9+p+YxQoT1wI7r9q+/U/MYo",
  "UPcvQH2G79/8Akj51/Er/ALGj9z+pk59cL9zcK/z1T+jFE1BSvXC/c3Cv89U/oxRNQe74Ps8fP7nguT1rAAAvlYtnq7+SDYnimemPDSAzfq7+S",
  "DYnimemPDSAx1/Wz8WaGroR8EAABASAfA39/YS4+rZPmlD54fA39/YS4+rZPmlDtHijh8D67QAA2xmwNWasrlX0bq+Z5sZTGrNWVyr6N1fM82K",
  "+R1M/BktPWR8SyjrSH2ltuJJba0mlST4jI+MhCvTCwLlYBY5V2idiP7DTHDn0p/LtVx3DMyT40Hmg/wAnPiMhdcZ700NF2HpK4aLYipQxd1JJc",
  "ikSjyIlqy7ZhZ/gLyLfzGRH0keew7/U2fq4MbZFXrI7uKIgAPkLht+pWpXJ1HrEJ6nVSE6piRFkINK2lpPIyMjHx41PESAd40dtM7EPRwWUOjT",
  "G6vbalGpyhVMjWwRmeZqbUWSm1cftT2Tz3pPdlwcB0nCNi5MlqjtGTi9YspfTdb9TfYTX2Qw3ley9n7Z7GqSex5+DaRnkOF6V2sEn6R9kLs+Ha",
  "cehUVyS1JW+9IU9IUpGZkRZElKSzPoP4hkQBWhiUwlyox3k0r7JLktgAAXCuBenRK5MeF/weh+aSILC9OiVyY8L/g9D80kJ9pdCPiX8PpMhxiP",
  "3Q7o61leeUPOj0WI/dDujrWV55Q86G0eCKL4gdr0K+VVhp1sj6KhxQdr0K+VVhp1sj6Kh0t6uXgztX014l2AABjDRGbNYvyPr68cH01gRPFsNY",
  "vyPr68cH01gRPGj2d1L8f5IUZnWLwAAAalEpfqfPuLij74p30ZAooJ16nz7i4o++Kd9GQKKDKZvtEv87B5j9UgAAKRZIBaSXKKxT+FVV9LdHOR",
  "0bSS5RWKfwqqvpbo5yNpX0F4Gcl0mB1jRO5S+GfX0TzhDk46xoncpfDPr6J5wgW9CXgzmHSResAAYs0QAAAAE7NcH9w8LvfNR+jHFExOzXB/cP",
  "C73zUfoxxdwvaI/52FbJ6pkzwAat1aNu0q6NJZEKs0yHVoR0aWv2NOjoeb2iNvI9lRGWZdI09k/Vwc+4Swjy5KPeZSAfYQ/mWw9/ES2fI8f1A/",
  "mWw9/ES2fI8f1Ap/M4+6X+Zv3jA1nUd2s6pCvNsJNbjD70nIvwW6ilaz+JJKP4hOgfYZruG9CqmHlbs6LTIlNotUgyITkSEwhlskvIUlRklJER",
  "H2xnnlxiAF62lPsK7qxblUaNmoUuU5EfQosu2Qoyz8R5Z/GJsG1WOfjr8yPJrcOT4aH++HVfbtXEG2K26eTVNqkWYs/8LbqVn9EfYeYfblMNvM",
  "uJdZcSS0OIPNKkmWZGR85GQ+uAKL6IesmoVmWJT7MxOanNFSmUx4NcitnIJbKSyS26gu2I0kRESk7WZcZFlmfGfRK1KUFroc4tsYNxl2lK1KJK",
  "TMzIiLeZnzD6/OPlwM3XjjiDWY6ycjT6/OkNKI8yNCn1mn9mQ31pNazy2JljzqBhYmbPq1SZUw5WJcdUdqGhRGSjQlXbKcy4syIizzzPiEylKN",
  "ajUozUozzMz4zHXAonXrOa01Ocq2M9IxPwKF0WjOUnVDXE66nZOdNblJIy+9+y0dBfp2M/jGAaJRZ1x1iDSqZGcm1Gc+iNGjNFmt1xaiSlJF0m",
  "ZkQrhpV4eowo1b9WtJJpUqk0+lR3VI4lOlPjG4ZeA1GoT5U0pVx75Iiojqpy+DJBAA9Hhtard9Yi2tbbz64rNYqsWnLfbSSlNpdeS2aiI+My2s",
  "/iF9vRasqpavQ84A71pf6LE7RcvyFTEy3qvb9SjE/AqjrRINxSdzraiLMiUkzI/EpJ844KOsJxsipR4M7Si4vks6ngBo43hpE3dHpFuQHEwScI",
  "ptXdQfsaGjnUpXEZ5cSS3mYt7g9hVRsFMOaLZ1CSr2DTWSQbzhFtvuHvW6vL75SjM/BnlzCaerA0jE2Hf0nDesvEii3GvskB1Z7mJpFkSfE4ks",
  "vykp6TFXwg2hZNz5D4dg1xIxUeUuIAACkvAZS0mMfPZy5NoW8+ZR0nsT5rav6w+dpJlzdJ8/FxcfWdJDEB+wcOX1QnTZqNQc9hsOJPJSCMjNSi",
  "6DIiPf0mQwcZmZmZnmZ85jyn0z27PHX5bjvRyWsn8H2efb8PE9o9AvRuvKf5rlLVRekF8V+0/Ds+PgfgAAeKn0AAAAAAAAAAAAAAAAAAAAAAAA",
  "Ae9wI7r9q+/U/MYoSJ7YEd1+1ffqfmMUJHuXoD7Dd+/8AyR86/iV/2NH7n9TJz64X7m4V/nqn9GKJqC4WllojQNKyPbDU645NvFQ1yVIOPFS92",
  "XspNkeeaiyy7EX6RnfggLf90mpeS2/4g9sxcqqqlQk9/wD9PDb6LJ2OUVuJigKdcEBb/uk1LyW3/EDggLf90mpeS2/4gt8+o976Mg5tb3HedXf",
  "yQbE8Uz0x4aQHPcAsII+A+FFEseLUnauxS+zbMx5om1OdkdW5vSRmRZbeXHzDoQzdslKyUlwbY4gnGKTAAAiO4HwN/f2EuPq2T5pQ+eH8Ndpaa",
  "5RKhTlOG0mZHcjm4RZmklpNOeXgzHK3M4fA+uUAp1wQFv8Auk1LyW3/ABA4IC3/AHSal5Lb/iDUc+o976MS82t7iYo1ZqyuVfRur5nmxo7ggLf",
  "90mpeS2/4g6do5avGk6O+KEO9Il5za09HYeYKI/BQ0lROJ2c9olme7xCG7MpnXKKe9okrx7IzTaNdgADODczDpfaD9v6SMBys0xbVBvxhBEzUt",
  "n7VKSXE2+Rce7cSy3lu4y3CSGLODF44I3M7QrwokilS072nVJzYkIz3LacLtVpPLjLi3keRkZD7Bo+DvCx7fxAozlJuWjQq5TXPbRp7CXUZ9JE",
  "Zbj8JBjj5s6VyZb0VLceNm9bmfXYAVhxT1UmH1zy5E2zK1UbPeczMoLn/ABkRJ5FkSdoycSWeZnmtXHuyIZ8uTVMYo09946NcVtVeMhOaDeeej",
  "OrPo2exqSXxrDmGbRP9rTxF0sayPYYhAaec1bOPyJJtFaMVxBHl2ZNYibJ+He4R/sHr6JqpcYqk205OqFsUlKlZLbenOuOILpyQ0aT/AFhK8ml",
  "fto6Kmx/ssxkP9I0Z6Y+hiO0t95Z7KW20mpSj6CIuMUusfVD0ph1Dl4X7LmNkrtmKLFSwak5fhubeR5/4TGwMJtGTDPBJlorStOFBmISRHUXiN",
  "+Ws+czdWZqLPoLIiz3ERCpZtCqPR3k8MSculuJy6NmrNvDEWRCrWIhP2bbZqJxUBacqjJRx7Owf9Tn0rLaL8EVUtG1abY1r0q3qNH9i0qmRm4k",
  "VnaNWw2hJJSWZ7z3Fxj5cAkvyJ3vWXAZV1RqX6T672I/dDujrWV55Q86Kk3DqlqDcFfqVUXiLUWVzZLsk200xsyQa1mrLPsm/LMfwcEBb/uk1L",
  "yW3/ED9Z1CXS+jFbxrdeBMUdr0K+VVhp1sj6Khs/ggLf90mpeS2/wCIPY4Pasei4Q4nW5eUe+59Seo0opSIjlPQhLpkRlkaiWeXH0DpZm0Sg0n",
  "2dzOYY1ikm0bYAAGaHJmzWL8j6+vHB9NYETxf/SAwej494T1uxpVTdpDFTNk1TGWidU32N5DpZJMyI8zRlx84x1wQFv8Auk1LyW3/ABA6wsmqm",
  "txm9+ouyKZ2TTiiYoCnXBAW/wC6TUvJbf8AEDggLf8AdJqXktv+IL/PqPe+jKvNre4/k1Pn3FxR98U76MgUUHANE7RIgaKkO5Y8G45NwlW3I7i",
  "1SIyWexdiJwiIslHnn2T9g7+EGTONl0px4Ma0xcK1F8QAAKpMQC0kuUVin8Kqr6W6OcirWIequoeIN/3NdLuIFQhu1upyamuMinIUlo3nVOGgj",
  "NZZkW1ln4B5/ggLf90mpeS2/wCINNDNoUUm/oxNLGtbb0JijrGidyl8M+vonnCG4uCAt/3Sal5Lb/iD1GF2q6omGOItuXYxf0+e9RpzU1EVynI",
  "Ql00KI9k1Es8s8uPIE82iUWk/owjjWqSbRuEAAZkcgAAAATs1wf3Dwu981H6McUTHAdLHRJgaVcK2o8645NvFRHJDiFR4yXuy9lJsjI81Fll2P",
  "9otY0413RnLgiC6LnW4x4kOhr3VacqRHUkz52x33ggLf90mpeS2/wCIOraNGr9pWjbiWV4Q7xmVx4obsP2K/CQ0nJez220Sz4tnoDi/MpnVKMX",
  "vaF9ePZGabRrMAAZ0bgYK1imhhNxI7JiZY8ApFwRmMqvTWE/bJrSCyS8gvvnEpLIy41JIsszLI96gJqrZUzU4kdkFZHks+t842tlxTbiTQtJml",
  "SVFkZGXGRkP1Fs9IHQMwzx8kO1R2I7a9zOHtLq9IJKTeP8A5zR9ovpzLZVuLtstwyPc+qJvCMparfvii1BG0eyioMOxzJPNmaSXv+IaGvOpmv1",
  "PRimeLZF7lqYEH5Sk1KIiIzM9xEXON623qi73lLI69e1Cp6CUWZQGnpJmXPvUlvIxq7ALV74Y4IS2qtIYdvC42z2m6hV0pNtg8+Npku1SfF2yt",
  "pW7cZZ5DmzOpgtz1ZxHGsk960OE6ufQtn0CdDxXviEqJI7Ht0KlSEbLiNov+0uEe9Pan2ics9+10DQmsV5G+IP/AMf/APsIw0iOe4/4Px8esJK",
  "9YkqpO0hiq9g2prLROqb7E+28WSTMiPM2yLj5wjd7svjZPsa+Qz9UoVuET6/w6Bo993zDX4TUz0psb64IC3/dJqXktv8AiD52wtVVQ7Fvm3bla",
  "xBqEt2jVGPUUx101tKXTadS4STPsm4j2cs/CHcs2hxaT+jFsca1NPQ7ppo4AJ0hMEapSYjaDuKnZ1CkrVzvILe3nzEtOafAZkZ8Qhu+w5FfcZe",
  "bU082o0LbWWSkqI8jIy5jIfZAGJsXtV5auJ+I9duqHds23G6s/wCyV06PBQ6224ZFtmkzWW5Ss1ZZbtrILsLKjSnCx7i3k0OxqUeJJ2n1CTSZ8",
  "adCfXFmRnUvMvtK2VtrSZGlRHzGRkRi6OiHj21pD4K0m4nXG/s5GL2DV2m8i2ZSEltKy5iWRksi/wAWXMMwcEBb/uk1LyW3/EHbdFnQpLRbuip",
  "1Kl33OrNPqUcmZVLkQktNrUk80OZks8lJzUXFxKMhLl3UXw/S96+B0x67apb1uZpwAAJBkZC0ybtRUbopFAZVmmnMqeey/DcyyL4kpL9YZ2Hrc",
  "Wqm9WMTbnlPmZrOoPIIj5kpWaUl8RERDyQ+WttZbzto3XvtbS8FuX0R9kej+DHZ2y8fGj2RTfi97+rAAASGgAAAAAAAAAAAAAAAAAAAAAAAAPf",
  "YDFnjBa3vxPzGKECe+A3dgtb34XzGKED3L0B9ht/f/kj51/Er/saf3P6mAAB6ceQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE9sdqQdFxcudjLJLkxUh",
  "Pic7f94eCHdtL62n6ZiLHqxoP2LUoydheW7bRuUXjyNJ/GOEj5Z21jvG2lfU1ppJ/JvVfRn2R6P5Ky9k41yeusI6+KWj+qAAASmgAAAAAAAAAA",
  "AAAAAAAAAAAAAAPf4ClnjBa3vsvmMUHE9sBzMsX7Vy/vifmMUJHuXoF7Db+/wDyR86/iV/2NP7n9TOD6Q+mZY2jPcFLo91wq3KlVGKctlVKjNO",
  "oJBLNOSjW6gyPMugxyfhYcHO9F4eT4/1gcB1u/dYsbqRfn1DBQ9sx8KqyqM5cWeG25E4TcUVz4WHBzvReHk+P9YDhYcHO9F4eT4/1gSMAWPy+n",
  "4kXO7C+Wj3pE2xpK2lPuK1Y1TiwYU5VPcTVGUNOG4TaHDMiQtZbOTid+fHnuHldITTQsTRpuOnUW6oVclS58Y5TSqXGadQSNo05Ga3UGR5l0Dj",
  "GqQ7gV1fCZ30WMOF63Duw2f1Krzygshjwlkup8C7K2SpU+00NwsODnei8PJ8f6wHCw4Od6Lw8nx/rAkYAZ/l9PxKXO7CufCw4Od6Lw8nx/rA0H",
  "gDpB21pH2hJuO149SjQGJSoi0VNlDThrJJGZkSFrLLJRc4gSK2aqDk+Vnrx3zbYp5eJXTXyo8SxRfOyfJkbXAACUYgAAAHwd9XhCw9sqvXRUkP",
  "OU6jQX6hJRGSSnVNtINaiSRmRGrJJ5EZl4xkvhYcHO9F4eT4/1gaB0oeTZin8F6l6M4IFhth41d8W59hRyLpVNKJXPhYcHO9F4eT4/wBYDhYcH",
  "O9F4eT4/wBYEjADD8vp+JU53YWYw01kOF2Kt+0S0aPTLnaqdXkpix1y4TCGkrPPLaNL6jIt3MRjVYhLoX8qjDPrhv5jF2gpzKYUTSh3F/HslbF",
  "uQAAC8tAAAAGcsdtO/DzR6vxdpXLAuCTU0xm5RrpsRlxrYXns71OpPPcfMOecLDg53ovDyfH+sDI2tH5U7/U0P98ZFGgpwqp1xk9dWhVZk2Rm4",
  "ornwsODnei8PJ8f6wHCw4Od6Lw8nx/rAkYAm/L6fiR87sPsD4JYy0LHvD2FeVuMTo9KluutNt1FtLbxG2s0KzJKlFlmR5bxy3HXTww80er8XaV",
  "ywLgk1NMZuUa6bEZca2F55b1OpPPcfMPhtWfySLc9+zvSFjDutG5U8jqaH++FdOPCeRKp8FqXbLZRqU1xZrnhYcHO9F4eT4/1gC1sGDZ/+U3eX",
  "/x8f6wJGAGn5fT8SlzuwrqWtewaP/yu7i/+PY+sDVWHOIVExVsqk3Vbsv2ZSKmwT7KzLJSc+NCy+9Uk8yMuYyMfXgG2dW1pTrwxvZOHdwyyTa1",
  "ffL2G68rIoc1WRJyM+JDm4jLiJWyfOedbIwYxg5VcUTU5TlLSZWoAAIhmeDxsxkoeAmHs28rjYnSKVEcaacbpzaXHjNxZITklSklxmWe8Zr4WH",
  "BzvReHk+P8AWB6vWXcke5ffkH0lAjCHGHi13V8qfHUX5F8656RK58LDg53ovDyfH+sBwsODnei8PJ8f6wJGAL35fT8StzuwuTo86Z9i6S9yVOi",
  "WpCrkWXT4nsx1VUjNNING2lGSTQ6szPNRcxDvQlXqiu7HevUJekNiqgSZVUabXCPAZUTdkOVIAAz/AKVGmLamjLRFMvmms3fJa24NDaXkZ57ic",
  "eV94j9p5ZF0lXhCVkuTFasllJRWsjutUq0GhwHZ1RmMQIbJZuSJLhNtoLwqMyIhlzFXWV4O4dPPQ6XPl3rUm8yNuiNZx0qLLIlPrNKTI8+Nvb4",
  "jzyEwMdNJu/8ASFrKpd1Vp1UBCv8AhqPFUbcOOWZ5ZNkeSlb/AG6s1H05ERFykO6tnRW+1/IWzy3wgii9c1v032Y4VGw4j+xcu0OdUlbefhJKM",
  "h55rW73wmRtOWNQFs5+0S+8lX62Z/MMEgLqw6F+yVnkWvtKRW5rftqQoq9hxsM5FsnTqltKLpzJaCGksJNYDg3i083DauBds1VZ7KYFwtlGNZ7",
  "i7VwjU0eZnkRbe0eR9qIlgIp4FMlu3HeOVYuO8+x/HkNS2G32HEPMuJJaHG1EpKknvIyMuMh/oIb6OumjiHo7S249PqC65bJqI3aDUnDWzl0tK",
  "PM2T3n7Xce7MjyIV10ftI6z9I60kVm2ZexLaSkp1KkGRSYaz+9UXOnPPJRbj/YE2RiTo3veu8Y1Xxt3dp1MAAUiyZpxr0/sN8BsQ59mXFT7ikV",
  "WE20445T4jLjJk42S05KU8k+JRZ7uMeF4WHBzvReHk+P9YGLtZXyurp96wPRWxl0aGrBpnXGT11aFNmTZGbSK58LDg53ovDyfH+sBwsODnei8P",
  "J8f6wJGAJfy+n4nTndh9hHCDFSj414d0i86C1LYpNUS4phuc2lDxEhxTZ7SUqURb0HxGe7IeyGdtXxyQcP/AM1L9MeGhnnm47K3XVpaaQk1LWs",
  "8kpIt5mZ8xDPWxULJRXYxtB8qKbP3HgMTsfMPcGoqn7yuynUQyLMo7izckK4vasoJTiuMuJJ7t/EMK6X+spllPm2hhFLSzHbJTMu6EkSlrVvI0",
  "xs9xEX/AKnHn7XLIjOeFVq06u1B+fUpsioTn1Gt2TKdU644o+M1KUZmZ+Ewxo2fKa5Vj0X1KduUovSG8qjd+tqw6pUpTNvWvXq+hKlJOQ/2OIh",
  "WR7lJIzUoyPj7Ykn4BzSbrf6r7JX7Ew2h+x8+07NVF7eXhybyE7gDOODQuzUpvJtfaUSha3+qdnT7Lw2h9h++7DVF7XxZt5D3lv63SxpUkkVqy",
  "a9TmNne7DeZkqz/ACVGjd8YliAHg0P9kFk2rtLo4babGDOKZMtUm9oUOe4Sc4FXJUJ5Kj+9LshElZlz7ClF4R29l5uSyh1pxLrS0kpC0HmlRHx",
  "GRlxkPrfjs+B2l1iZgFLQVv3A9Ko+ZG5RakpT8RRZ79lBn9rM/wAJBpM92eeQpWbN7a38yxDM99F3AGY9GDTysjSEaiUiapNrXqothVKluF2KS",
  "vpjuH7fP8EyJRHmWRkWZ6cCedcq5cma0YwjKM1rFnkcUcOYOJ9pyKPMMmnf6yNJyzNlwuJXi5jLoMYEvOzKpYdfkUirxzYksnuV964nmWk+cjF",
  "KR47E7C2j4pUM4FTb7G+3mqNMbIuyMq8HSXSXOMD6S+jcdsQ9fRuuivKS7n/J/P4ek+ifpXPYc+b5H6qJPzi+9fDvXmt/GdQD1GIWHVYw1rzlM",
  "qzBp3mbMhJfa30cykn/ANOMh5cfP91NmPY6rY8mS3NM+m6L6smqN1MlKMt6a4MAACEnAAAAAAAAAAAAAAAAAAAAOjaPMb2VjHbSfwX1OfqoUf8",
  "A0FABhfRVh+ysZKavLMmI77p+DtDL51DdA949BIcnZs5d839onzd+JFnK2rXDugvrKRLHW791ixupF+fUMFDeut37rFjdSL8+oYKHumJ1ETwvI",
  "62QAAFwrlYdUh3Arq+EzvosYcL1uHdhs/qVXnlDumqQ7gV1fCZ30WMOF63Duw2f1Krzygir9ufn9hnP2ZGEgAA9FgFbNVByfKz1475tsSTFbNV",
  "ByfKz1475tsLdodR5lzE6w2uAAMyOQAAADmGlDybMU/gvUvRnBAsX00oeTZin8F6l6M4IFjQbN6EvEVZnSQAADgXnadC/lUYZ9cN/MYu0IS6F/",
  "Kowz64b+YxdoZ7aXWR8Bth9B+IAACgvgAAAEdtaPyp3+pof74yKNda0flTv9TQ/3xkUa/G6mHgILusl4gAAWSEs5qz+SRbnv2d6QsYd1o3Knkd",
  "TQ/3xuLVn8ki3Pfs70hYw7rRuVPI6mh/vhFj+2T8/uM7vZ4+RkUAAPRYAAAAWT1fmlMjHbDdNvVyUa71t5pLUlTqs1TI/E2+XSfElXhyP74awH",
  "19cFMXa3gbiTRrwoLxolQXSN1gz7SSyZ/bGVl+CpOZdJbjLIyIxd/CzEqjYvWBRrtoEhMim1NgnU5H2zauJbauhSVEaTLpIZnNx/VT5UeDHONb",
  "6yPJfFHBdZdyR7l9+QfSUCMIs9rLuSPcvvyD6SgRhDLZ3Uvx/sU8vrPIAABoUjd+qK7sd69Ql6Q2KqCVeqK7sd69Ql6Q2KnTJjNPiPypDiWY7C",
  "FOOOKPclJFmZn4iIZfP69+Q6xeqRw/S70n6XozYcOVA9iXc9RJTFIp579tzLe6suZtGZGfSZkRce6Jd5XlWsQLmqFw3DUHqpWJ7puyJT6s1KPo",
  "8BEWRERbiIiIh0vSyx6m6Q2M1YuJxak0dhZw6TFz7VqMg8kn+Us81n4VZcREONh1iY6ohq+LF19rslu4IAAC8VgA/dllyQ6hppCnXFmSUoQWZq",
  "PoIh81IsO5okdb79u1ZlhBbSnXILqUpLpMzTkONUg0PggAByAHt8G8YbkwMvuBdVsTFRpsZRE6yZn2KS1mW004XOlX7NxlkZEPEAOGlJaPgcpt",
  "PVH2AMB8bKDpAYbU27qA5k0+XY5URSs3Ij6fbtL8JcZHzkZHzjoYjfq59IZ7CDGaPbdRfP+TF1LTDeStWSY8nP7S6Xx9ofgVn96QsgMnlUeos5",
  "K4dg8ps9bDXtIvayvldXT71geitjLo1FrK+V1dPvWB6K2MujS4/Uw8EJ7esl4gAAWCIt1q+OSDh/wDmpfpjw4nrPdJuXY9vxMMLdlHGqdaZ9kV",
  "aS2rJbUQzMktF0G4ZHmf4Kcvvt3a9XweWiDh/+al+lvCS2k7iNJxWx8ve45Dputv1J1mMR/eR2j7GykvEhCfjzPnCDHqVmVOT4Jv7jW2xwpil2",
  "o5eAAH4qAAOx4e6HuMeKdEbrFtWJPmUxwiU1KkOsxEOkfEaDeWjbLwpzIdZTjBayehyouW5I44A7VdOhfjdZqNupYcVg2ySazXBSiYlJFx5myp",
  "ZF8Y49UqXMo8tcWfEfhSke2YkNm2tPjSZEY4jOM+i9TlxceKP5gAe2wYwmrWN+JFFs6hIL2ZUHiSt9RGaI7Rb3HV+BKcz8O4i3mQ7NqK1Zwk29",
  "Eaj1amjAnE6+lYhXDCN22bdeIobbqe0lTiyUn8pLZGSjL8I09BkK1Dy2F+HNIwlsGi2lQmSZptLjpZQeWSnFcalq/xKUZqPwmPUjJZFzvscuzs",
  "H1NaqjoAABVJjy+ImHtKxJtx+lVRklZkamJBF27DmW5ST+cucT4u22JtmXHUKLUEbMqG6basuJRcyi8BlkZeMUvGN9MagfY+/qdU0t7KKhEyNZ",
  "FxrbPI/2GkeX+nGza7MVZ8V+uLSb7092/wemniew/h3ta2rMls2ctYTTaXdJb93itdfA4CAAPDz6HAAAAAAAAAAAAAAAAAAAAO06I8pqPi62hw",
  "8lPwXm2/yu1V8yTG3ROfCW4f5L4kW9UTVsNty0JcP/Ao9lX7DMUYHu3oJep7Psp7Yy+jS/sz5w/EjGlXtOu/snD6pvX7oljrd+6xY3Ui/PqGCh",
  "vXW791ixupF+fUMFD3bE6iJ4TkdbIAAC4VysOqQ7gV1fCZ30WMOF63Duw2f1Krzyh3TVIdwK6vhM76LGHC9bh3YbP6lV55QRV+3Pz+wzn7MjCQ",
  "AAeiwCtmqg5PlZ68d822JJitmqg5PlZ68d822Fu0Oo8y5idYbXAAGZHIAAABzDSh5NmKfwXqXozggWL6aUPJsxT+C9S9GcECxoNm9CXiKszpIA",
  "ABwLztOhfyqMM+uG/mMXaEJdC/lUYZ9cN/MYu0M9tLrI+A2w+g/EAABQXwAAACO2tH5U7/U0P8AfGRRrrWj8qd/qaH++MijX43Uw8BBd1kvEAA",
  "CyQlnNWfySLc9+zvSFjDutG5U8jqaH++Nxas/kkW579nekLGHdaNyp5HU0P8AfCLH9sn5/cZ3ezx8jIoAAeiwAAAADZOrk0piwev07JuGQabSu",
  "N5KW3Vq7WFMPIkLPPiQvclXh2T5jGNgI8jzLjEVtcbYOEu07wm4SUkWe1lp56I1ymW8vZkH0lAjCNxV7Sm/nt0BbmtS4Z5PXrbz9PStTqvtk2I",
  "UptKHv8RpzShR9JpM96hh0VcKuVUJQl2P+xPkTU5KS7gAAL5VN36orux3r1CXpDY1trFcV3sMNGqsx4L5sVO4nE0dlaTyUlteZvGX/tpUnwbZG",
  "Mk6orux3r1CXpDY9NrfLsUusYeWwhfatsSak6jPnUpLaD/+rgRWQ5eakxnCXJxmydQAAeiwD0mHGH9YxTvmjWnQWPZFWqsgmGUHxFuM1KV0JSk",
  "lKM+YiMebFDdUdhrHnXDeV9SWEuPQGm6ZDcUWfY1OZrcNPh2UpLPoMy5xBfb6mtzJaoesmomwtHHRAsTR2t9huBTY9XuVaC9mV+YwlT7it2ZN5",
  "59jRmXtU9BZ5nvHcXGW3UGhaErQZZGlRZkZD9wGRnOU3ypPVj6MVFaIx9piaBVsYvW7Urks2mRqDfcdpTyUw2ybYqRlmZocQWREtW/Jwizzyzz",
  "LikFKjOwpLsd9tTT7SzbcbWWRpUR5GRl0kY+x8Iu6xvC6LhtpMVeRTmExqdcDDdXQ2gskpdXml7LxuJUv/OHWz75Sbqk/AXZVSS5aMvAAB2LT/",
  "SNJdhyWpDDimn2lk424g8lJUR5kZH0kYvro34oFjJgfZ92qNPsufAQUtKeIpCO0eyLmLbSoy8BkIDCt2qjuhdY0fatSVr2jpNadQkj5kuIQsvi",
  "zNQVbRhrUpdzL2JLSbj3mM9ZXyurp96wPRWxl0ai1lfK6un3rA9FbGXRdx+ph4IrW9ZLxAAAsERavQXcUzoSWg4jPbRBnqLLpKS+Iv1dxTtVmr",
  "V7ZT6zPPp2jFq9X+yiTodWGy4WbbjExCi6SOW+RiO+LtoyrCxSu23ZjZtyKbVJEYyMssyS4okqLwGWRl4DIKcNr11q+P82X8hf8cH8DyIAAbFA",
  "/3gSG4s6M+6ymQ024la2VcSyIyM0n4+IX0wMxwsnG2zYVRs6qx5DbcdsnqcRpRIhHllsONZ5pyyyz4jy3GYgIPkbfuSrWlVmapRKnLpFSYPNqX",
  "BfUy6jpyUkyMhSycZZCW/RosU3eqfDifYyHicSsFrGxfpLlPvC2KdXGVEZJcfZInmj6W3SyWg/CkyEpcNdZnjHYvYWKpLp94wUZEpursZPGnPf",
  "k62aTzy3ZqJReAxrjDPWr4aXUpli66TU7MkryJTh/8bGSef4aEkvL/IEk8O+p6xWvgMo5FU9z+px3SP1Wc6hRX65hPNdq8dsjW7b9QWXsgi/5L",
  "nEv8lWR9BnxDvert0WTwUw+XdlxQFx70uBsjW1IRsuQoueaGsj3pUrcpRcftS+9GoLMv628RaM1VrXrtPr9OcIjKRT5CXUluzyVkfaqLPek8jL",
  "nIfPjpPKtlD1U/wD6do0Vxly4gAAUiyAAAAB5fEDDmiYl0dFOrcdTjba+yNOtK2XG1cWaVeEuMuceoAQ3U15FbqtipRfFPgT0X241kbqZOMo70",
  "1uaOLx9EmwWUmS2qg8Z865Rl8xEOJ6QWj9Fwxgxq1RpLz9Lee7A4zIyNTKjIzSZKLjI8j4xtQcC0x6ymJh7TqeRl2SZOSrL/ChJmf7TSMJ6QbE",
  "2ZTsy62FMYyitU0tHr2fPgej+jHpDtfI2vRTO+U4zejTeq003+GnHcY2AAHgB9NAAAAAAAAAAAAAAAAH5IzSZGRmRlvIyFM7amuVK3KVLd/rZE",
  "Rp1fjUgjP5xPnC3D+XiVeUKjxiNLSj7JJeItzTRH2yj+YvCZCijDDcVhtlpJIabSSEpLiIiLIiHsnoBj2xjfe1+h6JfFrXX5a/U8H/EzJplPGx",
  "k9Zx5TfwT00+en0Ja63fusWN1Ivz6hgob11u/dYsbqRfn1DBQ+iMTqInzlkdbIAAC4VysOqQ7gV1fCZ30WMOF63Duw2f1Krzyh3TVIdwK6vhM7",
  "6LGHC9bh3YbP6lV55QRV+3Pz+wzn7MjCQAAeiwCtmqg5PlZ68d822JJitmqg5PlZ68d822Fu0Oo8y5idYbXAAGZHIAAABzDSh5NmKfwXqXozgg",
  "WL6aUPJsxT+C9S9GcECxoNm9CXiKszpIAABwLztOhfyqMM+uG/mMXaEJdC/lUYZ9cN/MYu0M9tLrI+A2w+g/EAABQXwAAACO2tH5U7/U0P98ZF",
  "GutaPyp3+pof74yKNfjdTDwEF3WS8QAALJCWc1Z/JItz37O9IWMO60blTyOpof743Fqz+SRbnv2d6QsYd1o3KnkdTQ/3wix/bJ+f3Gd3s8fIyK",
  "AAHosAAP9pEN+IllT7K2iebJ1s1py20GZkSi6SzI9/gAB/iAAAD8ktSSURGZEosjIj4y4/wDoQ/AAAAAAADd+qK7sd69Ql6Q2PgNbBPVK0k6Sw",
  "Z9pGtuMgi8b8hRn/wDb9g+f1RXdjvXqEvSGx5vWtRlMaTMBaiyJ63IrifCXZpCfnSYUr21+Befs3mY0AADYogVx1UFNRF0cavLyLskq4pBmr/C",
  "llgiL9O1+kSOFdtVJORJ0aqiwR9vGuKSky8BssKI/2n+gLdodT5lzE6w2aAAMyOQJi63ymtovDDyeRETjsGSyZ9JJcSZfSMU6Ey9b9LQq5cOYu",
  "f2xMSW4ZeA1oIvomL+D18fP7FXJ6pk8AABqRIBTPU+zFLt3E6KZ9o1LgOkXhUh8j+gQmYKYanyMpNCxRfMu0XJpyCPwpTIM/pEKGd7PLy+5axu",
  "tRnHWV8rq6fesD0VsZdGotZXyurp96wPRWxl0T4/Uw8ERW9ZLxAAAsERbrV8ckHD/APNS/THhmPWiaMc6TUG8XbehnJZNpEavNMpzU3slstyDL",
  "nTkRIUfNknmzMtOavjkg4f/AJqX6Y8NBTYUepQ3okthuVFfQbbrLyCWhxJlkaVEe4yMuYxlfXOjIlNd7Hnq1ZSovuR9cMBRfSt1Y8liRLufCFs",
  "n461G4/a7islN85nHWZ9sX+BWRlzGfEJ8V+3qnatXk0qs0+TS6lGVsPRJbRtuNn0Gk940dV8LlrBieyuVb0kj48AATkYAAAB6Kx8RLmw1rLdVt",
  "auzqFUEGR9mhPGjay5lFxKLwGRkKPaK+s4i3VMgWviumPS6i7sss3Iykm47y+IuzoLc2Z/hJyTnxkkhL8BWux671pJb+8lrtlW/0s+yAy83IaQ",
  "60tLrS0kpK0HmlRHxGR85D9xOPVk6V86qS28Irpm+ydhlTlAlPq7ciSRqXGM+ciSRqTnvIiMuIiIqODL3Uyom4SHddisjykAABASgAAAAYu0ub",
  "0buC/2KPGXtsUdnsbhlxG8vtlfoLZLx5jZshw2mHFkWZpSZkXTuEzbgqL1XrtQnSFGp+RIW6sz6TUZjzL07zZU4deLH/wDR7/COn82vkeu/hxs",
  "+N+fbmS//ACWi8ZarX5J/M+PAAHhh9FgAAAAAAAAAAAAfkiMzyLeY/A7hoxYQN35X11ypo2qPS3U5NHxPvbjJJ+Atxn05kQYbPwbdpZMMWlfql",
  "9F2vyFe09o0bKxJ5mQ/0xXzfYl8WzuujPhgqwrJTOnNE3V6qSX3SMu2bb+8QfhyPMy6Ty5h2EfgiIiyLcQ/I+osHDq2fjQxaejFaf3fm958ebR",
  "z7dp5dmZe/wBU3r4dy8EtxLHW791ixupF+fUMFDeut37rFjdSL8+oYKG6xOoiZHI62QAAFwrlYdUh3Arq+EzvosYcL1uHdhs/qVXnlDumqQ7gV",
  "1fCZ30WMOF63Duw2f1Krzygir9ufn9hnP2ZGEgAA9FgFbNVByfKz1475tsSTFYtVVVoMHACsNyZseOs626ZJddSk8uxt8xmF2f1PmW8XrDcID4",
  "7+UdJ76QvlCP9w/lHSe+kL5Qj/cZnRjnVHyID47+UdJ76QvlCP9w/lHSe+kL5Qj/cGjDVHgdKHk2Yp/BepejOCBYvhpMyWZejPik6w6h5pVr1P",
  "JbaiUk/+Gc5yEDw/wBm9CXiK8zpIAABwLztOhfyqMM+uG/mMXaEItDV5uNpR4auuuJabTV2zUtZkREWR8ZmLmfyjpPfSF8oR/uM/tJf8kfAa4f",
  "QZ8iA+O/lHSe+kL5Qj/cP5R0nvpC+UI/3CjRl/VHyID47+UdJ76QvlCP9x/rGrNPmuk1HnRn3TLMkNPJUf6CMGjDUkFrR+VO/1ND/AHxkUa61o",
  "/Knf6mh/vjIo12N1MPAQ3dZLxAAAskJZzVn8ki3Pfs70hYw7rRuVPI6mh/vjcWrP5JFue/Z3pCxh3WjcqeR1ND/AHwix/bJ+f3Gd3s8fIyKAAH",
  "osAoFW9FlOM2gDh3eFAhG5eVu0+U5sMJzXNiFJfUtrIt6lJ9snn9sRe2E/RcPQHLLRFw596v+lPBdm2SqjGcexlvGgpycX3EPDLI8j3GA2RrGN",
  "Fk8Hr+O9qBGJNo3E8pS2mk5Jgyz3qQfQle9Sf8AMXMWeNxcqsjbBTj2lecHCTiwAAJToAAAAbv1RXdjvXqEvSGx8nrebZWxftg3CSc0SqY9AUr",
  "oNp3bIv8A+5X6B8Zqiu7HevUJekNjSWtCw1dvPR2+z0Rk3pVszm5iySWaiYX9rcP4jUhR+AjPmCSc+RnJv/NwyjHlYzI/AAB2LQKR6oi/miRfd",
  "luukT5mzVmGzPeaS+1OGXiM28/GQm4Pe4F4v1XArFGh3lSDNb0B37dH2skyWFFk40rwKSZ+I8j4yIV8ir11TgiWqfq5qR9gYB4LBrG208d7NiX",
  "FalSblsOoSb8VRkT8Rwy3tuo40qI8y6DyzIzLIx70ZBpxej4j9NNaoCPmtEv5i7NJE6PFeS81btOZhOGk8yJ5ebq0/ES0kfQZGXMKJaU+lTbOj",
  "ZZMmVKktTbokNmimUdtRG444ZblrL71tPGZnx8RZmYh9cVfnXVX6lWqm+qVUahIclSXlnma3FqNSj/SZhzs6l8p2vh2C/LsWnIR8cAAHwrArLq",
  "m7ZVS8CLgq605HVK0vYUfOlttCfnNQk2hCnFpSkjUpR5ERFmZmLz6KOF7mD+j7ZdtSW+x1FqEmRNTzlId+2OJP8k1bP8AlCvaM+TUo97LuJHWe",
  "vcS51lfK6un3rA9FbGXRqLWV8rq6fesD0VsZdFzH6mHgivb1kvEAACwRFutXxyQcP8A81L9MeGiRnbV8ckHD/8ANS/THh7/AEhsb6Ro+4WVa7q",
  "opC3GE9ihQ1KyVKkq9o2XPx7zy4kkZ8wx9sXK6UVx1f3NBBpVpvuOkkolGZEZGZHkeR8Q8HipgTYeNcBMW8rahVk20mlqS4jZfZI/wHU5KT4s8",
  "hHXDbTcxSw4xMql4tVtVWXWJSpNTpU4zVEkmZ8RII/tZkW5JpyyIiLeW4UowB1g+GWNLLMGoTk2bchkRKp9WcJDTqv+U97VXiPZV4D4xYtxLqP",
  "1R3+BDC+u3c/qcJxb1SUKS85Mw3u1yEk8z+xdeR2VJH0IfQRGRdBKSo+lQyLidoS4yYUtuyKpZsyoU5veqdRi9mNEXOaibzUkvCpJELmNPNyGk",
  "OtLS42siUlaDzJRHxGR84/cdq8+6G6W84ni1y4bj63zja2lmhaTQouNKiyMh+ou7jrol4c490WYzW6FHh1lxB9grkFtLUplfMo1EXbl0pVmR+P",
  "Iyhpc1FO3LjqtJU6l9UCW7FN1HEvYWadovHkHWPkxyE9Fo0LrqXU958aAALhXPQ4eXZKsO+7euKE6piVS57MtC0nlkaFkr9BkRl8Y+wxS56KrT",
  "Ik1v+rksoeT4lJIy+cfXGH2G8LOyFhlaXZf637ExNrPp7CnMI9ppfpfiMsN9JHqAAAjGYAAAB+DLMsjGHNIvB2VYFzyKtEaNygVB03G3EFuYWe",
  "821dG/My6S8Q3IP5qjTotXhOw5sduXFdTsuMvJJSVF4SMZzbuxattY3qZPSS3xfc/7PtNV6O7fu9H8v18FyoS3Sj3r4fFdny7SYQDYt56HtvVh",
  "96TQZ79FcXmZRll2Vkj8GfbEXxmM1YjYV1/DCp+xaxG+0rP7TMZzUy8XgPmPwHvHg20/R7aGyk53w1h7y3r+680j6T2R6UbM201XjWaT92W5/2",
  "fk2ePAAGbNWAAAAAAAABQfAm0k2bhdRIRo2JDzXsp88t5rc7bf4iMi+IYWsKiFct7UKlq9pLmssq/JNZZ/szFJkIS2hKEESUpLIiLiIh636A4i",
  "lZdlvsSivPe/sjxH8S85xrx8GL4tyfluX3Z+wAA9lPBSWOt37rFjdSL8+oYKG9dbv3WLG6kX59QwUNZidRERZHWyAAAuFcrDqkO4FdXwmd9FjD",
  "hetw7sNn9Sq88od01SHcCur4TO+ixhwvW4d2Gz+pVeeUEVftz8/sM5+zIwkAAHosA/wBWpb7Cdlt5xtPHkhRkQ/yAAH9H2Rl/3p7/AFDD7Iy/7",
  "09/qGP5wBoB/R9kZf8Aenv9Qw+yMv8AvT3+oY/nAGgFZ8FXFu6rOtLWpS1Ha1dzUo8zPfJEmBWXBH/usa18Fq788kSaC3E6VniXMjow8AAAGRT",
  "Pyham1EpCjSouIyPIyH+/2Rl/3p7/AFDH84AA/o+yMv8AvT3+oYfZGX/env8AUMfzgDQD+j7Iy/709/qGNWasqZIe0rqQlx9xxP2Nm9qpZmX9U",
  "MljV+rF5WFH6tm+aFbJ6mfgTU9ZHxP69aPyp3+pof74yKNda0flTv8AU0P98ZFBjdTDwC7rJeIAAFkhLOas/kkW579nekLGHdaNyp5HU0P98bi",
  "1Z/JItz37O9IWMO60blTyOpof74RY/tk/P7jO72ePkZFAAD0WAXF0Ciy0RsOfej/pLwh0LjaBpZaI+HHvN70l0KdpdUvEvYfTfgdQxWwxomMWH",
  "9ZtG4YxSKbUmTbM8u2aXxodQfMpKiJRH4OgQgxnwlrWCOI9YtCvMqblwXTJt3LJMhk97bqD50qLf48y4yMfYMGS9YRotFjphudx0NgjvK3WlOs",
  "pSnNU2MWZuMflF7ZPhIy++zJfhZHqp8mXBlvJq9ZHlLiiOAD8qSaFGlRGlRHkZHxkPwNMJgAAADd+qK7sd69Ql6Q2Kg3Nb0K7bcqlEqLRP0+pR",
  "XYkhtRblNrSaVF+gzEvtUV3Y716hL0hsVUGYzt17fgOsXqkfX3xwwnqmCOKVfs+qtKS7T5CiYdMtz7B72nU9JKSZH48y4yMeEFj9PzRIVpA2Y1",
  "cVuMp/lvQ21dhbIv+3x95qY/KI+2SfTmX32ZR0kR3Yr7jLzamnm1GhbayyUlRbjIyPiMPMa9Xw17e0WXVOqWnYf5gAC2QHzVp3rcFiVVFStut1",
  "Cg1BHFJp0lbDnizSZZl4B1ibpw46z6UVOdxJq6Y5Fltsk009/qoQS/j2hw0B0lXCT1kkzspSjuTP7KvWqhcFQen1SfJqU55W07JmPKddWfSpSj",
  "MzPxj+MAHc6gAHoLBsOuYm3fTLZtyA7UqvUXiZZYaSZ+NSj5kpLMzUe4iIzMcNpLVglruO6aA+AMjG/HSmyJMfatq3VpqVSdWXaqNJ5tNF0mpZ",
  "Fu/BSoxa4iyLIuIch0XdHik6NuF0K3IRplVV7KRVahlkcmQZbzLoQn2qS6C6TMx18ZXLv8AX2arguA8oq9VDR8SL2sr5XV0+9YHorYy6NRayvl",
  "dXT71geitjLo0eP1MPBCi3rJeIAAFgiLbaAEhqJoc2G++4lplpiYtbizySlJS3zMzPoyE3tOrSeXpE4puMUt1ZWdQlLjUxBnufVnk5IMv8Zlu/",
  "wAJJ5zMdIvjHqt4dav3C+y6GxLiKuZicmbVkNqJtMdMx4lMJc4ttfOWeZJ/KGIgrxqNLJ3S73p8y7dbrCNa7kAAA0KR07DLSZxQwfURWpelUp8",
  "Yv/BOO+yIx/8AsuEpBH4SLPwjv1D1q2L9ObQifCt+rbJZGtyIppSvCeysi/QQxmAgnRVPfKKJI2zjuTNe37rPsXrxokumQCpNsoktm0uTTmFG+",
  "lJlkewtaj2TyPjIsy4yMj3jIjjinVqWtRrWozNSlHmZn0mP1AdoVQqWkFocSnKfSeoAAEp0PQYe2tJve+7et6I2b0mqVBiGhBFnma3CT/1H2Gq",
  "ZBRTKbEht/wBXHaQynxJIiL5hMPVaaOsit3dIxWrENSaXSici0g3U5E9JUnZccSR8ZISo058W0o+dO6oozm0LVOxQXYN8SHJi5PtAAAVF4AAAA",
  "AAAAD4i6bVpd6USRSqvFRLhvlkaVcaT5lJPmMukh8uA6ThG2LhNap8UySuydM1ZW9JLemuKZP7GnCCbhNcJMmpUqkys1Q5RlvMudCuhRft4xzo",
  "b80hrNbvLCyroJBHLgtnOjqy3kbe9RfGnaL4yGAx84+lGyIbIzuRT1c1qvh3ry+zR9V+h+3J7b2dy73/yQfJl8e5+a+qYAAGQNyAAAAdk0UrZK",
  "vYqx5a07TVLZXKP8r2qf2qz+IbiGX9Cy35bKLjrLrCm4jxNRmXVFkTiiNRry6cs0/pGoB9D+hmN6jZMJtaObb+ui+iPlz09yuc7bnBPVVqMfpq",
  "/qwAANyedEsdbv3WLG6kX59QwULU6VmhHTdKW6KLWpt0yqCumQ1Q0tR4qXSWRrNe0ZmosuPIcP4IGge6NUvJzfrjQY+XTXVGMnvQquosnY5JEx",
  "gFOeCBoHujVLyc364cEDQPdGqXk5v1xZ59R730ZDza3uPUapDuBXV8JnfRYw4XrcO7DZ/UqvPKG7tFfRqh6L1i1O2oVbfrzc6pKqJyJDCWjQam",
  "m29nIjPd9rI8/CPFaVOg9TdKK7KTXJt0y6C5T4ZxEsx4qXSWRrNW0ZmosuMKoX1rKdre4vSqk6FDTeRZAU54IGge6NUvJzfrhwQNA90apeTm/X",
  "DXn1HvfRlHm1vcTGAU54IGge6NUvJzfrhwQNA90apeTm/XBz6j3vow5tb3ExgFOeCBoHujVLyc364cEDQPdGqXk5v1wc+o976MObW9xMYBTngg",
  "aB7o1S8nN+uHBA0D3Rql5Ob9cHPqPe+jDm1vceswR/wC6xrXwWrvzyRJoXds3Rth2foyzMHW62/JhyKZNpp1RTBJcSUk3M1bGeWaeyHuz35DLf",
  "BA0D3Rql5Ob9cUsfKqrlNyfFli6mc1FJcETGAU54IGge6NUvJzfrhwQNA90apeTm/XF3n1HvfRlfm1vcTGAU54IGge6NUvJzfrhwQNA90apeTm",
  "/XBz6j3vow5tb3ExgFOeCBoHujVLyc364cEDQPdGqXk5v1wc+o976MObW9xMYav1YvKwo/Vs3zQ0VwQNA90apeTm/XHUNG/V6UnR1xRiXpEvGZ",
  "WXo8d6OUR6GhpJk4nZM9olHxCG7MpnXKMXvaJK8eyM02jGGtH5U7/U0P98ZFFj9JbV+UrSQxNXeMy8JlEeVEZiexWIaHU5N59ttGouPMcp4IGg",
  "e6NUvJzfrjijMphXGMnvSCzHslNtImMApzwQNA90apeTm/XDggaB7o1S8nN+uJ+fUe99GR82t7jserP5JFue/Z3pCxh3WjcqeR1ND/fFPNHTBG",
  "No84V0+yYlUdrLEN554pbzRNqV2Rw1mWyRmW7PIcX0ltX5StJDE1y8Zl4TKK8uI1E9isQ0OpIkZ79o1Fx5hVTfXDJlY3uepesqlKlQS3kcQFOe",
  "CBoHujVLyc364cEDQPdGqXk5v1w159R730ZR5tb3ExhcjQP3aJGHHvJ30h0Zw4IGge6NUvJzfrjaOCOFzGC2FdvWTGnuVNikMqZTLdbJCnM3FL",
  "zNJGZF7bL4gvzcmu6CjB9paxqZ1ybkj3IAATDEkjrItFg8K74/nAtyB2O06+8Zy22E9pBmnvMsuZLm9Rc2ZKLduIYqH2HcSsO6NivY1YtSvx/Z",
  "FLqbCmXSL2yD+9Wk+ZSTyMj6SGG+CBoHujVLyc364fY2dBQ5Nr3oV3Y0nLWC3ExgFOeCBoHujVLyc364cEDQPdGqXk5v1xb59R730ZBza3uOa6",
  "orux3r1CXpDYqoMx6Kmg/TdFu7axXYV0yq85UYPsJTMiKlokF2RK9ojJR5+1y+MacCLLsjba5Q4DOiDhDkyAxjplavynY3PSrvsk2KNexpNUiM",
  "vJEapH0qP7x3m2uI+fpGzgEFdsqpcqDJZwjYtJH12r2sO4cOK/Iolz0eXRKowZkuNLb2T8ZHxKLwkZkfSPgR9hDE/ByzMZaEukXjb0OtxDLtFP",
  "IydZP8ACbcLJSD8KTIYuxK1SFv1Jb0ixrxlUVZ5miFVmCkteLsiTSpJeEyUH1W0K5LSzcxXPEmujvJgANb3FqvMb6K6pMOJQ662R7nIFSJOZeJ",
  "5LZjzyNXPj0tzZ/kc2XhVUo5F+nbF1ZFL/bXzK3qbF+yzNIDZVpaqvGCuPt/ZiXb9uRjP7Yb8xT7qS/wpaSpJn4DUXjGm8LtVPh3arzEq76xUL",
  "ykIMlHHIvYcZR9BpSo1mX+cRTzaIfta+BJHHsl2aE4MFtH698fbjapNo0d2WnbIn6g6RoixU86nHMsiy6CzUfMRiv2ijof2zoxW+tTBlWLsmJI",
  "p1adRkeW77U0X3jZHv6TPeZ8RF2m2LTotlUaPSaBSYdFpjCdlqJBYSy2kvAlJEXxj5YJMjMnf+lbkMaseNe972AAAvLZF7WV8rq6fesD0VsZdF",
  "g9InV2UnSDxWqd7y7zm0d+c0w0cRmEhxKextJbI9o1Ee/ZzHNeCBoHujVLyc3640dOZTCuMW96Qosx7JTbSJjAKc8EDQPdGqXk5v1w4IGge6NU",
  "vJzfribn1HvfRkfNre47HoX2Jb+JGg/ZNCuakxq1SZLMsnI0pG0X/AGt/eR8aTLmMsjIZe0itVpXrcXMrWFcpVwUwjNz7BTHCTMaTx7LazyS6R",
  "dB5Ky/CPjoTgNhKxgXhRQbHjVFyqsUpLqUzHWybU5turc3pIzIstvL4h78JFkzrslKt7mxk6YzglJb9D659xWxV7RqjtNrdMl0ioNHkuNNZU04",
  "nxpURGPjB9hi/8KbOxUpa6ddtt02vxVFkRTY6VLR4UL9sg/CkyMZTvrVTYXXA447b1VrNrLUeaWkOlKZT4MnO2y/zfGGle0a5dNaFKeJJdF6kk",
  "wG+Lr1RN6w1qO275oVVb5iqbD0NX/0J0h4KZqt8b4yjJtm35ZF98zU8iP8AWQkW1lUPhJFd0WL9kyIA15B1WuN0tZJdbt6ER/fP1MzIv1EKMdP",
  "sbVDVx9Tbl437T4SS9vHokVcgz8Tjmxl+oYJZdEeMgVFj/ZJ6DW2iZoA3RjlOjV26mJVsWMhSVG86nscqeXGaWUqLcnpcMst+7a35UAwZ0B8I8",
  "GpbFRYoirjrbO9FQriif2FfhIbyJCT6D2cy5jGjEpJCSSkiSkiyIiLcQW37Q1XJqXmXK8TR6zPjLXtilWXb1PodEhNU6kwGUsRorJZJbQXEX/8",
  "Ap7zHygAEnHexkAAAAAAAAAAAAAAAAfw11lMiiVBpZZoXHcSZeA0mJlOp2XVpLiIzIU5qjK5FNltN/wBYtlaU+MyMiEzKjEegVCTGkIU2+y4pt",
  "xCiyNKiPIyHjv4gReuNLT3v6T3b8MZLk5cdfc/qP5gHscPsJrkxMlG3RoWbCDycmPmaGG/GrLefgIjMdNrWhvdUCn9ngVOn1OQks1Rk7TRn4Em",
  "ZZH8eQ87xti7RzKnfRTKUe/8At3+Wp6nl7f2Xg3LHyciMZ92vDx7vPQ4CO+aNmBMK/ku3DXiU7So7vYmYhbifWW8zUf4JZluLj+fjdbtCt25Uf",
  "YFSpcqHLz2SacaPNX5PT8Q3jgZar9nYW0KnymjZmG0b7zZlkaVLUasj8JEZF8Q0fonsmObtFrKr1jWtWmu3Xcn9Xp8DK+m225YGy4vDs0la9E0",
  "9/J0bbT+S1+J7WDAjUuI1FhsNxozSdlDTSSSlJdBEQ/oAB9BJKK0XA+YW3J6t7wAAOTgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAADylbwqtC5KmdRqdvQZc1WRqeW12yvysuP4wAQ201Xx5NsVJfFJ/csU5F2NLl0TcX3ptfY9HT6dFpURuLCjNRIzZZIZYQSEJLwEW4f0AAlS",
  "UVouBA25Nyk9WfqpCVGRmkjMt5ZlxD9gAcnAAAAAAAAB//Z"
  ].join("");

})();

/* FFI share cards - single self-contained engine.
   Modeled on the School District Report Card page, which is the only share
   implementation that has never broken in the field. Everything the card path
   needs lives in the page: the logo, the painters, the preview overlay and the
   share/save handoff. Nothing is fetched from the CDN at tap time, so there is
   no stale-copy failure mode, no wrapper race, and no waiting on a network
   round trip after the user taps. */
(function(){
  if (window.FFI_CARDS) return;
  var W = 1080, H = 1920;
  function ltBlob(c, cb){
    function viaURL(){
      try {
        var d = c.toDataURL('image/png'), b = atob(d.split(',')[1]);
        var u = new Uint8Array(b.length), i;
        for (i = 0; i < b.length; i++) u[i] = b.charCodeAt(i);
        cb(new Blob([u], { type: 'image/png' }));
      } catch (e) { cb(null); }
    }
    if (!c.toBlob) { viaURL(); return; }
    var done = 0;
    try {
      c.toBlob(function(bl){ if (done) return; done = 1; if (bl) cb(bl); else viaURL(); }, 'image/png');
    } catch (e) { if (!done) { done = 1; viaURL(); } }
  }
  function wrap(x, text, max){
    var w = String(text).split(' '), lines = [], cur = '', i, t;
    for (i = 0; i < w.length; i++) {
      t = cur ? cur + ' ' + w[i] : w[i];
      if (x.measureText(t).width > max && cur) { lines.push(cur); cur = w[i]; } else { cur = t; }
    }
    if (cur) lines.push(cur);
    return lines;
  }
  function round(x, rx, ry, rw, rh, r){
    x.beginPath();
    x.moveTo(rx + r, ry);
    x.lineTo(rx + rw - r, ry); x.quadraticCurveTo(rx + rw, ry, rx + rw, ry + r);
    x.lineTo(rx + rw, ry + rh - r); x.quadraticCurveTo(rx + rw, ry + rh, rx + rw - r, ry + rh);
    x.lineTo(rx + r, ry + rh); x.quadraticCurveTo(rx, ry + rh, rx, ry + rh - r);
    x.lineTo(rx, ry + r); x.quadraticCurveTo(rx, ry, rx + r, ry);
    x.closePath(); x.fill();
  }
  function paint(o, logo, cb){
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, W, H);
    x.fillStyle = '#fe5f05'; x.fillRect(0, 0, W, 20); x.fillRect(0, H - 20, W, 20);
    x.textAlign = 'center';
    var top = 300;
    if (logo && logo.naturalWidth) {
      var lw = 520, lh = lw * logo.naturalHeight / logo.naturalWidth;
      x.drawImage(logo, (W - lw) / 2, 110, lw, lh);
      top = 110 + lh + 130;
    }
    if (o.title) {
      x.fillStyle = '#13294b';
      var tfs = 68, tl;
      x.font = '900 ' + tfs + 'px Montserrat, sans-serif';
      tl = wrap(x, String(o.title).toUpperCase(), 900);
      while (tl.length > 3 && tfs > 44) {
        tfs -= 3; x.font = '900 ' + tfs + 'px Montserrat, sans-serif';
        tl = wrap(x, String(o.title).toUpperCase(), 900);
      }
      for (var ti = 0; ti < tl.length; ti++) { x.fillText(tl[ti], W / 2, top + tfs * 0.86); top += tfs * 1.08; }
      if (o.sub) {
        top += 16;
        var sb_fs = o.sub_big ? 76 : 38;
        x.fillStyle = o.sub_big ? '#fe5f05' : 'rgba(19,41,75,0.62)';
        x.font = (o.sub_big ? '900 ' : '700 ') + sb_fs + 'px Montserrat, sans-serif';
        var sbl = wrap(x, String(o.sub), 900);
        while (o.sub_big && sbl.length > 2 && sb_fs > 46) {
          sb_fs -= 4; x.font = '900 ' + sb_fs + 'px Montserrat, sans-serif';
          sbl = wrap(x, String(o.sub), 900);
        }
        for (var sbi = 0; sbi < sbl.length; sbi++) { x.fillText(sbl[sbi], W / 2, top + sb_fs * 0.82); top += sb_fs * 1.12; }
      }
      top += 46;
    }
    var T = o.tbl, n = T.length, i;
    var has_sub = false;
    for (i = 0; i < n; i++) if (T[i][4]) has_sub = true;
    var row_h = Math.min(has_sub ? 150 : 118, (H - 240 - top) / n);
    /* center short tables */
    top += Math.max(0, ((H - 240 - top) - n * row_h) / 2);
    var fs = Math.min(50, Math.round(row_h * (has_sub ? 0.34 : 0.46)));
    var has_rank = false;
    for (i = 0; i < n; i++) if (String(T[i][0] || '') !== '') has_rank = true;
    var has_ext = false;
    for (i = 0; i < n; i++) if (T[i][5]) has_ext = true;
    var rk_r = has_ext ? 110 : 148;
    var vl_r = has_ext ? 360 : (has_rank ? 430 : 330);
    var nm_l = has_ext ? 392 : (has_rank ? 474 : 374);
    var ext_r = W - 70, nm_right = has_ext ? 300 : 80;
    var nm_fs = fs, nw;
    x.font = '700 ' + nm_fs + 'px Montserrat, sans-serif';
    for (i = 0; i < n; i++) {
      nw = x.measureText(String(T[i][2])).width;
      while (nm_fs > 22 && nw > W - nm_l - nm_right) {
        nm_fs -= 2; x.font = '700 ' + nm_fs + 'px Montserrat, sans-serif';
        nw = x.measureText(String(T[i][2])).width;
      }
    }
    if (has_ext) {
      x.fillStyle = 'rgba(19,41,75,0.55)';
      x.font = '800 24px Montserrat, sans-serif';
      x.textAlign = 'right';
      x.fillText('CURRENT PENSION', vl_r, top - 16);
      x.fillText('LIFETIME BENEFIT', ext_r, top - 16);
    }
    var sub_fs = Math.max(17, Math.round(nm_fs * 0.64));
    if (has_sub) {
      x.font = '600 ' + sub_fs + 'px Montserrat, sans-serif';
      for (i = 0; i < n; i++) {
        nw = x.measureText(String(T[i][4] || '')).width;
        while (sub_fs > 13 && nw > W - nm_l - 80) {
          sub_fs -= 1; x.font = '600 ' + sub_fs + 'px Montserrat, sans-serif';
          nw = x.measureText(String(T[i][4] || '')).width;
        }
      }
    }
    for (i = 0; i < n; i++) {
      var r_top = top + i * row_h, hi = !!T[i][3];
      var mid = r_top + row_h * (has_sub ? 0.46 : 0.66);
      if (hi) { x.fillStyle = 'rgba(254,95,5,0.11)'; round(x, 70, r_top + 2, W - 140, row_h - 4, 8); }
      if (i) { x.fillStyle = '#e6eaf1'; x.fillRect(70, r_top, W - 140, 1); }
      x.fillStyle = hi ? '#fe5f05' : '#13294b';
      x.textAlign = 'right';
      x.font = '800 ' + Math.round(fs * 0.88) + 'px Montserrat, sans-serif';
      x.fillText(String(T[i][0]), rk_r, mid);
      if (o.val_orange) x.fillStyle = '#fe5f05';
      x.font = '900 ' + fs + 'px Montserrat, sans-serif';
      x.fillText(String(T[i][1]), vl_r, mid);
      x.fillStyle = hi ? '#fe5f05' : '#13294b';
      x.textAlign = 'left';
      x.font = '700 ' + nm_fs + 'px Montserrat, sans-serif';
      x.fillText(String(T[i][2]), nm_l, mid);
      if (has_sub && T[i][4]) {
        x.fillStyle = 'rgba(19,41,75,0.58)';
        x.font = '600 ' + sub_fs + 'px Montserrat, sans-serif';
        x.fillText(String(T[i][4]), nm_l, mid + sub_fs * 1.35);
      }
      if (has_ext && T[i][5]) {
        x.textAlign = 'right';
        x.fillStyle = hi ? '#fe5f05' : '#13294b';
        x.font = '800 ' + Math.round(fs * 0.86) + 'px Montserrat, sans-serif';
        x.fillText(String(T[i][5]), ext_r, mid);
      }
    }
    x.textAlign = 'center'; x.fillStyle = 'rgba(19,41,75,0.55)';
    var sfs = 40, sl;
    x.font = '600 ' + sfs + 'px Montserrat, sans-serif';
    sl = wrap(x, o.source || '', 900);
    if (sl.length > 1) { sfs = 34; x.font = '600 ' + sfs + 'px Montserrat, sans-serif'; sl = wrap(x, o.source || '', 920); }
    var sy = H - 80 - (sl.length - 1) * (sfs + 8);
    for (i = 0; i < sl.length; i++) { x.fillText(sl[i], W / 2, sy); sy += sfs + 8; }
    ltBlob(c, cb);
  }
  function ready(fn){
    var done = 0;
    var go = function(){ if (!done) { done = 1; fn(); } };
    if (document.fonts && document.fonts.load) {
      try {
        document.fonts.load('900 90px Montserrat');
        document.fonts.load('800 40px Montserrat');
        document.fonts.load('700 40px Montserrat');
      } catch (e) {}
      if (document.fonts.ready && document.fonts.ready.then) { document.fonts.ready.then(go); }
      setTimeout(go, 1200);
    } else { go(); }
  }
  /* Number cards: the hosted renderer shrinks the big number to fit the card's
     HEIGHT but never its WIDTH, so long values like $4,747.53 run off both
     edges. This painter fits width and height, and wraps the source line. */
  function paintNum(o, logo, cb){
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, W, H);
    x.fillStyle = '#fe5f05'; x.fillRect(0, 0, W, 20); x.fillRect(0, H - 20, W, 20);
    x.textAlign = 'center';
    var top = 300;
    if (logo && logo.naturalWidth) {
      var lw = 520, lh = lw * logo.naturalHeight / logo.naturalWidth;
      x.drawImage(logo, (W - lw) / 2, 110, lw, lh);
      top = 110 + lh + 120;
    }
    var src_fs = 40, src_l = [];
    x.font = '600 ' + src_fs + 'px Montserrat, sans-serif';
    if (o.source) {
      src_l = wrap(x, String(o.source), 900);
      if (src_l.length > 2) { src_fs = 34; x.font = '600 ' + src_fs + 'px Montserrat, sans-serif'; src_l = wrap(x, String(o.source), 920); }
    }
    var src_top = H - 80 - (src_l.length ? (src_l.length - 1) * (src_fs + 8) : 0);
    var pre_fs = 56, pre_l = [];
    if (o.pre) {
      x.font = '800 ' + pre_fs + 'px Montserrat, sans-serif';
      pre_l = wrap(x, String(o.pre).toUpperCase(), 900);
      while (pre_l.length > 2 && pre_fs > 40) {
        pre_fs -= 4; x.font = '800 ' + pre_fs + 'px Montserrat, sans-serif';
        pre_l = wrap(x, String(o.pre).toUpperCase(), 900);
      }
    }
    var num_txt = String(o.num == null ? '' : o.num);
    var num_fs = 320;
    x.font = '900 ' + num_fs + 'px Montserrat, sans-serif';
    while (num_fs > 96 && x.measureText(num_txt).width > 900) {
      num_fs -= 8; x.font = '900 ' + num_fs + 'px Montserrat, sans-serif';
    }
    var lab_fs = 74, lab_lh, lab_l = [];
    if (o.label) {
      x.font = '700 ' + lab_fs + 'px Montserrat, sans-serif';
      lab_l = wrap(x, String(o.label), 880);
    }
    var con_fs = 52, con_l = [];
    if (o.contrast) {
      x.font = '700 ' + con_fs + 'px Montserrat, sans-serif';
      con_l = wrap(x, String(o.contrast), 860);
    }
    var avail = (src_top - 80) - top;
    var block_h = function(){
      lab_lh = lab_fs * 1.32;
      return (pre_l.length ? pre_l.length * (pre_fs * 1.2) + 34 : 0)
        + num_fs * 0.78 + 56 + lab_l.length * lab_lh
        + (con_l.length ? 52 + con_l.length * (con_fs * 1.3) : 0);
    };
    while (block_h() > avail && (num_fs > 120 || lab_fs > 52)) {
      if (num_fs > 120) { num_fs -= 10; }
      else {
        lab_fs -= 3;
        x.font = '700 ' + lab_fs + 'px Montserrat, sans-serif';
        lab_l = o.label ? wrap(x, String(o.label), 880) : [];
      }
    }
    var y = top + Math.max(0, (avail - block_h()) / 2);
    if (pre_l.length) {
      x.fillStyle = '#fe5f05'; x.font = '800 ' + pre_fs + 'px Montserrat, sans-serif';
      for (var pi = 0; pi < pre_l.length; pi++) { y += pre_fs; x.fillText(pre_l[pi], W / 2, y); y += pre_fs * 0.2; }
      y += 34;
    }
    x.fillStyle = '#fe5f05'; x.font = '900 ' + num_fs + 'px Montserrat, sans-serif';
    y += num_fs * 0.78;
    x.fillText(num_txt, W / 2, y);
    y += 56;
    if (lab_l.length) {
      x.fillStyle = '#13294b'; x.font = '700 ' + lab_fs + 'px Montserrat, sans-serif';
      for (var li = 0; li < lab_l.length; li++) { y += lab_lh; x.fillText(lab_l[li], W / 2, y); }
    }
    if (con_l.length) {
      y += 52;
      x.fillStyle = 'rgba(19,41,75,0.72)'; x.font = '700 ' + con_fs + 'px Montserrat, sans-serif';
      for (var ci = 0; ci < con_l.length; ci++) { y += con_fs * 1.3; x.fillText(con_l[ci], W / 2, y); }
    }
    if (src_l.length) {
      x.fillStyle = 'rgba(19,41,75,0.55)'; x.font = '600 ' + src_fs + 'px Montserrat, sans-serif';
      var sy = src_top;
      for (var si = 0; si < src_l.length; si++) { x.fillText(src_l[si], W / 2, sy); sy += src_fs + 8; }
    }
    ltBlob(c, cb);
  }
  function drawNum(o, cb){
    ready(function(){
      var src = window.FFI_CARD_LOGO || window.FFI_OP_LOGO || window.FFI_PTX_LOGO;
      if (!src) { paintNum(o, null, cb); return; }
      var im = new Image();
      im.onload = function(){ paintNum(o, im, cb); };
      im.onerror = function(){ paintNum(o, null, cb); };
      im.src = src;
    });
  }
  function drawTbl(o, cb){
    ready(function(){
      var src = window.FFI_CARD_LOGO || window.FFI_OP_LOGO || window.FFI_PTX_LOGO;
      if (!src) { paint(o, null, cb); return; }
      var im = new Image();
      im.onload = function(){ paint(o, im, cb); };
      im.onerror = function(){ paint(o, null, cb); };
      im.src = src;
    });
  }
  function paintBars(o, logo, cb){
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, W, H);
    x.fillStyle = '#fe5f05'; x.fillRect(0, 0, W, 20); x.fillRect(0, H - 20, W, 20);
    x.textAlign = 'center';
    var num = function(s){ var v = parseFloat(String(s).replace(/[^0-9.\-]/g, '')); return isNaN(v) ? 0 : v; };
    var i, y = 300;
    if (logo && logo.naturalWidth) {
      var lw = 520, lh = lw * logo.naturalHeight / logo.naturalWidth;
      x.drawImage(logo, (W - lw) / 2, 110, lw, lh);
      y = 110 + lh + 110;
    }
    if (o.pre) {
      var pfs = 64, pl;
      x.font = '800 ' + pfs + 'px Montserrat, sans-serif';
      pl = wrap(x, String(o.pre).toUpperCase(), 920);
      while (pl.length > 2 && pfs > 44) {
        pfs -= 3; x.font = '800 ' + pfs + 'px Montserrat, sans-serif';
        pl = wrap(x, String(o.pre).toUpperCase(), 920);
      }
      x.fillStyle = '#fe5f05';
      for (i = 0; i < pl.length; i++) { y += pfs; x.fillText(pl[i], W / 2, y); y += pfs * 0.22; }
      y += 28;
    }
    var hd = o.hed || o.title || '';
    if (hd) {
      var hfs = 94, hl;
      x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
      hl = wrap(x, hd, 950);
      while (hl.length > 3 && hfs > 56) {
        hfs -= 4; x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
        hl = wrap(x, hd, 950);
      }
      x.fillStyle = '#13294b';
      for (i = 0; i < hl.length; i++) { y += hfs * 0.92; x.fillText(hl[i], W / 2, y); y += hfs * 0.18; }
    }
    var sfs = 40, sl = [];
    x.font = '600 ' + sfs + 'px Montserrat, sans-serif';
    if (o.source) {
      sl = wrap(x, String(o.source), 900);
      if (sl.length > 2) { sfs = 34; x.font = '600 ' + sfs + 'px Montserrat, sans-serif'; sl = wrap(x, String(o.source), 920); }
    }
    var src_top = H - 80 - (sl.length ? (sl.length - 1) * (sfs + 8) : 0);
    var cfs = 50, clh = 64, cl = [];
    if (o.label) {
      x.font = '700 ' + cfs + 'px Montserrat, sans-serif';
      cl = wrap(x, String(o.label), 890);
      while (cl.length > 3 && cfs > 38) {
        cfs -= 2; clh -= 3; x.font = '700 ' + cfs + 'px Montserrat, sans-serif';
        cl = wrap(x, String(o.label), 890);
      }
    }
    var bub = o.bubble ? String(o.bubble).toUpperCase() : '';
    var pill_h = bub ? 108 : 0, pill_gap = bub ? 54 : 0;
    var cap_h = cl.length ? cl.length * clh + 40 : 0;
    var year_h = 100;
    var base = src_top - 90 - cap_h - pill_h - pill_gap - year_h;
    var B = o.bars, n = B.length;
    var bw = Math.min(250, Math.floor((820 - (n - 1) * 110) / n));
    var gap = n > 2 ? 110 : 170;
    var span = n * bw + (n - 1) * gap;
    var left = (W - span) / 2;
    var top = y + 70;
    var max_h = base - top - 108;
    if (max_h > 640) { top += (max_h - 640) / 2; max_h = 640; }
    if (max_h < 240) max_h = 240;
    var peak = 0;
    for (i = 0; i < n; i++) { peak = Math.max(peak, num(B[i][1])); }
    if (!peak) peak = 1;
    var vfs = 78;
    var fits = function(f){
      var k; x.font = '900 ' + f + 'px Montserrat, sans-serif';
      for (k = 0; k < n; k++) { if (x.measureText(String(B[k][1])).width > bw + 56) return false; }
      return true;
    };
    while (vfs > 34 && !fits(vfs)) vfs -= 2;
    x.fillStyle = 'rgba(19,41,75,0.16)';
    x.fillRect(left - 50, base, span + 100, 5);
    for (i = 0; i < n; i++) {
      var cx = left + i * (bw + gap) + bw / 2;
      var h = Math.max(14, max_h * num(B[i][1]) / peak);
      x.fillStyle = i === n - 1 ? '#fe5f05' : '#13294b';
      x.fillRect(cx - bw / 2, base - h, bw, h);
      x.font = '900 ' + vfs + 'px Montserrat, sans-serif';
      x.fillText(String(B[i][1]), cx, base - h - 34);
      x.fillStyle = '#13294b';
      x.font = '700 56px Montserrat, sans-serif';
      x.fillText(String(B[i][0]), cx, base + 78);
    }
    var below = base + year_h;
    if (bub) {
      var bfs = 58;
      x.font = '900 ' + bfs + 'px Montserrat, sans-serif';
      while (bfs > 34 && x.measureText(bub).width > 790) { bfs -= 2; x.font = '900 ' + bfs + 'px Montserrat, sans-serif'; }
      var pw = x.measureText(bub).width + 120;
      x.fillStyle = '#fe5f05';
      round(x, (W - pw) / 2, below + pill_gap, pw, pill_h, pill_h / 2);
      x.fillStyle = '#ffffff';
      x.textBaseline = 'middle';
      x.fillText(bub, W / 2, below + pill_gap + pill_h / 2 + 3);
      x.textBaseline = 'alphabetic';
      below += pill_gap + pill_h;
    }
    if (cl.length) {
      x.fillStyle = '#13294b';
      x.font = '700 ' + cfs + 'px Montserrat, sans-serif';
      var cy = below + 74;
      for (i = 0; i < cl.length; i++) { x.fillText(cl[i], W / 2, cy); cy += clh; }
    }
    if (sl.length) {
      x.fillStyle = 'rgba(19,41,75,0.55)';
      x.font = '600 ' + sfs + 'px Montserrat, sans-serif';
      var sy = src_top;
      for (i = 0; i < sl.length; i++) { x.fillText(sl[i], W / 2, sy); sy += sfs + 8; }
    }
    ltBlob(c, cb);
  }
  /* Change-since card: one labeled row per category, signed value and a bar.
     Negative changes read navy and grow left of center; growth reads orange. */
  function paintDelta(o, logo, cb){
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, W, H);
    x.fillStyle = '#fe5f05'; x.fillRect(0, 0, W, 20); x.fillRect(0, H - 20, W, 20);
    var D = o.delta, n = D.length, i, top = 300;
    x.textAlign = 'center';
    if (logo && logo.naturalWidth) {
      var lw = 460, lh = lw * logo.naturalHeight / logo.naturalWidth;
      x.drawImage(logo, (W - lw) / 2, 110, lw, lh);
      top = 110 + lh + 120;
    }
    var hd = o.hed || o.title || '';
    if (hd) {
      var hfs = 90, hl;
      x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
      hl = wrap(x, String(hd).toUpperCase(), 900);
      while (hl.length > 4 && hfs > 46) {
        hfs -= 4; x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
        hl = wrap(x, String(hd).toUpperCase(), 900);
      }
      x.fillStyle = '#13294b';
      for (i = 0; i < hl.length; i++) { x.fillText(hl[i], W / 2, top + hfs * 0.86); top += hfs * 1.06; }
      top += 10;
    }
    if (o.sub) {
      x.fillStyle = 'rgba(19,41,75,0.72)';
      x.font = '800 56px Montserrat, sans-serif';
      var sbl = wrap(x, String(o.sub), 900);
      for (i = 0; i < sbl.length; i++) { x.fillText(sbl[i], W / 2, top + 48); top += 68; }
    }
    /* source first, so the rows can claim every pixel that is left */
    x.fillStyle = 'rgba(19,41,75,0.55)';
    var sfs = 36, sl = wrap(x, o.source || '', 900);
    x.font = '600 ' + sfs + 'px Montserrat, sans-serif';
    sl = wrap(x, o.source || '', 900);
    if (sl.length > 2) { sfs = 30; x.font = '600 ' + sfs + 'px Montserrat, sans-serif'; sl = wrap(x, o.source || '', 920); }
    var src_top = H - 90 - (sl.length ? (sl.length - 1) * (sfs + 8) : 0);
    for (i = 0; i < sl.length; i++) { x.fillText(sl[i], W / 2, src_top + i * (sfs + 8)); }
    var val = function(s){ var v = parseFloat(String(s).replace(/[^0-9.\-]/g, '')); return isNaN(v) ? 0 : v; };
    var neg = function(s){ return /^\s*[-\u2212]/.test(String(s)) || val(s) < 0; };
    var av, max_pos = 0, max_neg = 0;
    for (i = 0; i < n; i++) {
      av = Math.abs(val(D[i][1]));
      if (neg(D[i][1])) { if (av > max_neg) max_neg = av; }
      else if (av > max_pos) max_pos = av;
    }
    var total = (max_pos + max_neg) || 1;
    top += 40;
    var space = src_top - 130 - top;
    var row_h = Math.min(230, space / n);
    top += Math.max(0, (space - n * row_h) / 2);
    var pad = Math.min(30, row_h * 0.16);
    var bar_h = Math.max(22, Math.min(40, row_h * 0.22));
    var lfs = Math.max(32, Math.min(46, Math.round(row_h * 0.22)));
    var vfs = Math.max(42, Math.min(72, Math.round(row_h * 0.34)));
    /* the value sits at the right margin, so the bars get the width that is
       left over; the label owns its own line above them */
    x.font = '900 ' + vfs + 'px Montserrat, sans-serif';
    var vw = 0;
    for (i = 0; i < n; i++) vw = Math.max(vw, x.measureText(String(D[i][1])).width);
    var span = (W - 180) - (vw + 40);
    var zero_x = 90 + span * max_neg / total;
    var lbl_h = lfs, bar_band = Math.max(bar_h, vfs);
    var cell_h = lbl_h + pad + bar_band;
    for (i = 0; i < n; i++) {
      var r_top = top + i * row_h + Math.max(0, (row_h - cell_h) / 2);
      var down = neg(D[i][1]);
      var col = down ? '#13294b' : '#fe5f05';
      x.textAlign = 'left';
      x.fillStyle = '#13294b';
      x.font = '700 ' + lfs + 'px Montserrat, sans-serif';
      var lbl = String(D[i][0]), lfs2 = lfs, lw2 = x.measureText(lbl).width;
      while (lfs2 > 24 && lw2 > W - 180) {
        lfs2 -= 2; x.font = '700 ' + lfs2 + 'px Montserrat, sans-serif';
        lw2 = x.measureText(lbl).width;
      }
      x.fillText(lbl, 90, r_top + lfs2 * 0.86);
      var band_top = r_top + lbl_h + pad;
      var by = band_top + (bar_band - bar_h) / 2;
      var len = Math.max(bar_h, span * Math.abs(val(D[i][1])) / total);
      /* axis only where the bars are, never behind the labels */
      if (max_neg > 0) {
        x.fillStyle = 'rgba(19,41,75,0.38)';
        x.fillRect(zero_x - 2, by - 12, 4, bar_h + 24);
      }
      x.fillStyle = col;
      round(x, down ? zero_x - len : zero_x, by, len, bar_h, bar_h / 2);
      x.textAlign = 'right';
      x.fillStyle = col;
      x.font = '900 ' + vfs + 'px Montserrat, sans-serif';
      x.fillText(String(D[i][1]), W - 90, band_top + bar_band * 0.5 + vfs * 0.35);
    }
    ltBlob(c, cb);
  }
  /* Three-column card: district, reading proficiency, spending per student.
     Column headers carry the wording so the rows stay short. */
  function paintCols(o, logo, cb){
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, W, H);
    x.fillStyle = '#fe5f05'; x.fillRect(0, 0, W, 20); x.fillRect(0, H - 20, W, 20);
    var R = o.cols, n = R.length, i, top = 300;
    x.textAlign = 'center';
    if (logo && logo.naturalWidth) {
      var lw = 440, lh = lw * logo.naturalHeight / logo.naturalWidth;
      x.drawImage(logo, (W - lw) / 2, 100, lw, lh);
      top = 100 + lh + 100;
    }
    var hd = o.title || o.hed || '';
    if (hd) {
      var hfs = 82, hl;
      x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
      hl = wrap(x, String(hd).toUpperCase(), 900);
      while (hl.length > 3 && hfs > 48) {
        hfs -= 4; x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
        hl = wrap(x, String(hd).toUpperCase(), 900);
      }
      x.fillStyle = '#13294b';
      for (i = 0; i < hl.length; i++) { x.fillText(hl[i], W / 2, top + hfs * 0.86); top += hfs * 1.06; }
      top += 6;
    }
    if (o.sub) {
      x.fillStyle = '#fe5f05';
      var cfs = 40, cl;
      x.font = '800 ' + cfs + 'px Montserrat, sans-serif';
      cl = wrap(x, String(o.sub).toUpperCase(), 880);
      while (cl.length > 2 && cfs > 30) {
        cfs -= 2; x.font = '800 ' + cfs + 'px Montserrat, sans-serif';
        cl = wrap(x, String(o.sub).toUpperCase(), 900);
      }
      for (i = 0; i < cl.length; i++) { x.fillText(cl[i], W / 2, top + cfs * 0.9); top += cfs * 1.18; }
      top += 12;
    }
    x.fillStyle = 'rgba(19,41,75,0.55)';
    var sfs = 30, sl;
    x.font = '600 ' + sfs + 'px Montserrat, sans-serif';
    sl = wrap(x, o.source || '', 900);
    if (sl.length > 3) { sfs = 26; x.font = '600 ' + sfs + 'px Montserrat, sans-serif'; sl = wrap(x, o.source || '', 920); }
    var src_top = H - 80 - (sl.length ? (sl.length - 1) * (sfs + 6) : 0);
    for (i = 0; i < sl.length; i++) { x.fillText(sl[i], W / 2, src_top + i * (sfs + 6)); }
    /* columns: district left, proficiency centered, spending right */
    var L = 70, pc = 640, rr = W - 70;
    var hds = o.colhd || ['District', 'Read at grade level', 'Spending per student'];
    x.font = '800 27px Montserrat, sans-serif';
    x.fillStyle = 'rgba(19,41,75,0.6)';
    var h1 = wrap(x, String(hds[0]).toUpperCase(), 330);
    var h2 = wrap(x, String(hds[1]).toUpperCase(), 230);
    var h3 = wrap(x, String(hds[2]).toUpperCase(), 230);
    var hrows = Math.max(h1.length, Math.max(h2.length, h3.length));
    top += 26;
    var hy = top;
    for (i = 0; i < h1.length; i++) { x.textAlign = 'left'; x.fillText(h1[i], L, hy + (hrows - h1.length + i) * 32 + 24); }
    for (i = 0; i < h2.length; i++) { x.textAlign = 'center'; x.fillText(h2[i], pc, hy + (hrows - h2.length + i) * 32 + 24); }
    for (i = 0; i < h3.length; i++) { x.textAlign = 'right'; x.fillText(h3[i], rr, hy + (hrows - h3.length + i) * 32 + 24); }
    top += hrows * 32 + 34;
    x.fillStyle = '#13294b';
    x.fillRect(L, top - 14, W - 140, 3);
    var space = src_top - 80 - top;
    var row_h = Math.min(170, space / n);
    var nfs = Math.max(24, Math.min(40, Math.round(row_h * 0.30)));
    var pfs = Math.max(28, Math.min(50, Math.round(row_h * 0.36)));
    for (i = 0; i < n; i++) {
      var ry = top + i * row_h, mid = ry + row_h * 0.66, tot = !!R[i][3];
      if (i) { x.fillStyle = '#e6eaf1'; x.fillRect(L, ry, W - 140, 1); }
      if (tot) {
        /* district total: tinted band under an orange rule */
        x.fillStyle = 'rgba(254,95,5,0.10)';
        round(x, L, ry + 3, W - 140, row_h - 6, 8);
        x.fillStyle = '#fe5f05';
        x.fillRect(L, ry, W - 140, 3);
      }
      x.textAlign = 'left';
      x.fillStyle = '#13294b';
      var nm = String(R[i][0]), nfs2 = nfs;
      x.font = '700 ' + nfs2 + 'px Montserrat, sans-serif';
      while (nfs2 > 20 && x.measureText(nm).width > 470) {
        nfs2 -= 2; x.font = '700 ' + nfs2 + 'px Montserrat, sans-serif';
      }
      x.fillText(nm, L, mid);
      x.textAlign = 'center';
      x.fillStyle = '#fe5f05';
      x.font = '900 ' + pfs + 'px Montserrat, sans-serif';
      x.fillText(String(R[i][1]), pc, mid);
      x.textAlign = 'right';
      x.fillStyle = '#fe5f05';
      x.font = '800 ' + Math.round(pfs * 0.86) + 'px Montserrat, sans-serif';
      x.fillText(String(R[i][2]), rr, mid);
    }
    ltBlob(c, cb);
  }
  function drawCols(o, cb){
    ready(function(){
      var src = window.FFI_CARD_LOGO || window.FFI_OP_LOGO || window.FFI_PTX_LOGO;
      if (!src) { paintCols(o, null, cb); return; }
      var im = new Image();
      im.onload = function(){ paintCols(o, im, cb); };
      im.onerror = function(){ paintCols(o, null, cb); };
      im.src = src;
    });
  }
  function drawDelta(o, cb){
    ready(function(){
      var src = window.FFI_CARD_LOGO || window.FFI_OP_LOGO || window.FFI_PTX_LOGO;
      if (!src) { paintDelta(o, null, cb); return; }
      var im = new Image();
      im.onload = function(){ paintDelta(o, im, cb); };
      im.onerror = function(){ paintDelta(o, null, cb); };
      im.src = src;
    });
  }
  function drawBars(o, cb){
    ready(function(){
      var src = window.FFI_CARD_LOGO || window.FFI_OP_LOGO || window.FFI_PTX_LOGO;
      if (!src) { paintBars(o, null, cb); return; }
      var im = new Image();
      im.onload = function(){ paintBars(o, im, cb); };
      im.onerror = function(){ paintBars(o, null, cb); };
      im.src = src;
    });
  }
  /* Donut card: title on top, the section's donut redrawn, small legend below. */
  function paint_pie(o, logo, cb){
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, W, H);
    x.fillStyle = '#fe5f05'; x.fillRect(0, 0, W, 20); x.fillRect(0, H - 20, W, 20);
    x.textAlign = 'center';
    var top = 300;
    if (logo && logo.naturalWidth) {
      var lw = 520, lh = lw * logo.naturalHeight / logo.naturalWidth;
      x.drawImage(logo, (W - lw) / 2, 110, lw, lh);
      top = 110 + lh + 116;
    }
    var src_fs = 38, src_l = [];
    x.font = '600 ' + src_fs + 'px Montserrat, sans-serif';
    if (o.source) {
      src_l = wrap(x, String(o.source), 900);
      if (src_l.length > 2) { src_fs = 32; x.font = '600 ' + src_fs + 'px Montserrat, sans-serif'; src_l = wrap(x, String(o.source), 920); }
    }
    var src_top = H - 76 - (src_l.length ? (src_l.length - 1) * (src_fs + 8) : 0);
    var t_fs = 66, t_l = [];
    if (o.title) {
      x.font = '900 ' + t_fs + 'px Montserrat, sans-serif';
      t_l = wrap(x, String(o.title).toUpperCase(), 900);
      while (t_l.length > 2 && t_fs > 46) {
        t_fs -= 4; x.font = '900 ' + t_fs + 'px Montserrat, sans-serif';
        t_l = wrap(x, String(o.title).toUpperCase(), 900);
      }
      x.fillStyle = '#13294b';
      for (var ti = 0; ti < t_l.length; ti++) { top += t_fs; x.fillText(t_l[ti], W / 2, top); top += t_fs * 0.18; }
      top += 54;
    }
    var P = o.pie, n = P.length, i;
    var row_h = 74, legend_h = n * row_h;
    var room = (src_top - 62) - top - legend_h - 46;
    var r = Math.min(268, Math.max(150, room / 2));
    var cx = W / 2, cy = top + r;
    var total = 0;
    for (i = 0; i < n; i++) total += Number(P[i][1]) || 0;
    var a0 = -Math.PI / 2;
    for (i = 0; i < n; i++) {
      var a1 = a0 + (Number(P[i][1]) || 0) / total * Math.PI * 2;
      x.beginPath(); x.moveTo(cx, cy); x.arc(cx, cy, r, a0, a1); x.closePath();
      x.fillStyle = P[i][2] || '#13294b'; x.fill();
      a0 = a1;
    }
    x.beginPath(); x.arc(cx, cy, r * 0.56, 0, Math.PI * 2); x.fillStyle = '#ffffff'; x.fill();
    var big = String(P[0][1]) + '%';
    var big_fs = Math.round(r * 0.44);
    x.font = '900 ' + big_fs + 'px Montserrat, sans-serif';
    while (big_fs > 40 && x.measureText(big).width > r * 0.95) { big_fs -= 4; x.font = '900 ' + big_fs + 'px Montserrat, sans-serif'; }
    x.fillStyle = '#fe5f05'; x.fillText(big, cx, cy + big_fs * 0.16);
    var cap = String(P[0][0]).toUpperCase(), cap_fs = 26;
    x.font = '800 ' + cap_fs + 'px Montserrat, sans-serif';
    while (cap_fs > 16 && x.measureText(cap).width > r * 1.0) { cap_fs -= 2; x.font = '800 ' + cap_fs + 'px Montserrat, sans-serif'; }
    x.fillStyle = '#13294b'; x.fillText(cap, cx, cy + big_fs * 0.16 + cap_fs + 16);
    var ly = cy + r + 46, lx = 150, rx = W - 150;
    for (i = 0; i < n; i++) {
      var is_first = i === 0;
      var mid = ly + row_h * 0.5;
      x.fillStyle = P[i][2] || '#13294b';
      ffi_pie_sq(x, lx, mid - 15, 30, 30, 5);
      x.textAlign = 'left';
      x.fillStyle = is_first ? '#fe5f05' : '#13294b';
      x.font = '800 40px Montserrat, sans-serif';
      x.fillText(String(P[i][0]), lx + 52, mid + 14);
      x.textAlign = 'right';
      x.font = '900 44px Montserrat, sans-serif';
      x.fillText(String(P[i][1]) + '%', rx, mid + 14);
      if (i < n - 1) { x.fillStyle = '#e6eaf1'; x.fillRect(lx, ly + row_h, rx - lx, 1); }
      ly += row_h;
    }
    x.textAlign = 'center';
    if (src_l.length) {
      x.fillStyle = 'rgba(19,41,75,0.55)'; x.font = '600 ' + src_fs + 'px Montserrat, sans-serif';
      var sy = src_top;
      for (i = 0; i < src_l.length; i++) { x.fillText(src_l[i], W / 2, sy); sy += src_fs + 8; }
    }
    ltBlob(c, cb);
  }
  function ffi_pie_sq(x, px, py, pw, ph, pr){
    x.beginPath();
    x.moveTo(px + pr, py);
    x.lineTo(px + pw - pr, py); x.quadraticCurveTo(px + pw, py, px + pw, py + pr);
    x.lineTo(px + pw, py + ph - pr); x.quadraticCurveTo(px + pw, py + ph, px + pw - pr, py + ph);
    x.lineTo(px + pr, py + ph); x.quadraticCurveTo(px, py + ph, px, py + ph - pr);
    x.lineTo(px, py + pr); x.quadraticCurveTo(px, py, px + pr, py);
    x.closePath(); x.fill();
  }
  function draw_pie(o, cb){
    ready(function(){
      var src = window.FFI_CARD_LOGO || window.FFI_OP_LOGO || window.FFI_PTX_LOGO;
      if (!src) { paint_pie(o, null, cb); return; }
      var im = new Image();
      im.onload = function(){ paint_pie(o, im, cb); };
      im.onerror = function(){ paint_pie(o, null, cb); };
      im.src = src;
    });
  }
  /* Two-column list card: title, optional subtitle, label/value rows. */
  function paintRows(o, logo, cb){
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var x = c.getContext('2d');
    x.fillStyle = '#ffffff'; x.fillRect(0, 0, W, H);
    x.fillStyle = '#fe5f05'; x.fillRect(0, 0, W, 20); x.fillRect(0, H - 20, W, 20);
    var R = o.rows, n = R.length, i, top = 300;
    x.textAlign = 'center';
    if (logo && logo.naturalWidth) {
      var lw = 460, lh = lw * logo.naturalHeight / logo.naturalWidth;
      x.drawImage(logo, (W - lw) / 2, 110, lw, lh);
      top = 110 + lh + 110;
    }
    var hd = o.title || o.hed || '';
    if (hd) {
      var hfs = 84, hl;
      x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
      hl = wrap(x, String(hd).toUpperCase(), 900);
      while (hl.length > 3 && hfs > 48) {
        hfs -= 4; x.font = '900 ' + hfs + 'px Montserrat, sans-serif';
        hl = wrap(x, String(hd).toUpperCase(), 900);
      }
      x.fillStyle = '#13294b';
      for (i = 0; i < hl.length; i++) { x.fillText(hl[i], W / 2, top + hfs * 0.86); top += hfs * 1.06; }
      top += 8;
    }
    if (o.sub) {
      var sfs2 = o.sub_big ? 52 : 40;
      x.font = '800 ' + sfs2 + 'px Montserrat, sans-serif';
      x.fillStyle = '#fe5f05';
      var sbl = wrap(x, String(o.sub).toUpperCase(), 880);
      for (i = 0; i < sbl.length; i++) { x.fillText(sbl[i], W / 2, top + sfs2 * 0.9); top += sfs2 * 1.2; }
      top += 10;
    }
    x.fillStyle = 'rgba(19,41,75,0.55)';
    var sfs = 36, sl;
    x.font = '600 ' + sfs + 'px Montserrat, sans-serif';
    sl = wrap(x, o.source || '', 900);
    if (sl.length > 2) { sfs = 30; x.font = '600 ' + sfs + 'px Montserrat, sans-serif'; sl = wrap(x, o.source || '', 920); }
    var src_top = H - 84 - (sl.length ? (sl.length - 1) * (sfs + 8) : 0);
    for (i = 0; i < sl.length; i++) { x.fillText(sl[i], W / 2, src_top + i * (sfs + 8)); }
    var head_row = (n > 1 && String(R[0][0] || '') === '') ? R[0] : null;
    var body = head_row ? R.slice(1) : R, bn = body.length;
    top += 30;
    var space = src_top - 90 - top;
    var row_h = Math.min(150, space / Math.max(bn, 1));
    top += Math.max(0, (space - bn * row_h) / 2);
    var wide = body.length && body[0].length > 2;
    var L = 80, RT = W - 80, MID = W - 300;
    if (head_row) {
      x.font = '800 30px Montserrat, sans-serif';
      x.fillStyle = 'rgba(19,41,75,0.6)';
      x.textAlign = 'right';
      if (wide) { x.fillText(String(head_row[1] || '').toUpperCase(), MID, top - 18); x.fillText(String(head_row[2] || '').toUpperCase(), RT, top - 18); }
      else { x.fillText(String(head_row[1] || '').toUpperCase(), RT, top - 18); }
    }
    x.fillStyle = '#13294b';
    x.fillRect(L, top - 8, W - 160, 3);
    var lfs = Math.max(26, Math.min(46, Math.round(row_h * 0.34)));
    var vfs = Math.max(30, Math.min(58, Math.round(row_h * 0.42)));
    for (i = 0; i < bn; i++) {
      var ry = top + i * row_h, mid = ry + row_h * 0.64;
      if (i) { x.fillStyle = '#e6eaf1'; x.fillRect(L, ry, W - 160, 1); }
      x.textAlign = 'left';
      x.fillStyle = '#13294b';
      var lb = String(body[i][0]), lf = lfs;
      x.font = '700 ' + lf + 'px Montserrat, sans-serif';
      while (lf > 20 && x.measureText(lb).width > (wide ? MID - L - 60 : RT - L - 240)) {
        lf -= 2; x.font = '700 ' + lf + 'px Montserrat, sans-serif';
      }
      x.fillText(lb, L, mid);
      x.textAlign = 'right';
      x.fillStyle = '#fe5f05';
      x.font = '900 ' + vfs + 'px Montserrat, sans-serif';
      if (wide) {
        x.fillText(String(body[i][1]), MID, mid);
        x.fillText(String(body[i][2]), RT, mid);
      } else {
        x.fillText(String(body[i][1]), RT, mid);
      }
    }
    ltBlob(c, cb);
  }
  function drawRows(o, cb){
    withLogo(function(im){ paintRows(o, im, cb); });
  }
  function withLogo(fn){
    ready(function(){
      var src = window.FFI_CARD_LOGO || window.FFI_OP_LOGO || window.FFI_PTX_LOGO;
      if (!src) { fn(null); return; }
      var im = new Image();
      im.onload = function(){ fn(im); };
      im.onerror = function(){ fn(null); };
      im.src = src;
    });
  }
  /* Show the finished card and let the user confirm before the share sheet opens.
     The Share button runs in its own tap, so the native share still works. */
  function ffiShareCard(blob, opts){
    opts = opts || {};
    if (window.FFI_SHARE_PREVIEW === false) { ffiShareNow(blob, opts); return; }
    var old = document.getElementById('ffi-share-preview');
    if (old && old.parentNode) old.parentNode.removeChild(old);
    var url = null;
    try { url = URL.createObjectURL(blob); } catch (e) {}
    var ov = document.createElement('div');
    ov.id = 'ffi-share-preview';
    ov.setAttribute('role', 'dialog');
    ov.setAttribute('aria-modal', 'true');
    ov.setAttribute('aria-label', 'Preview your card before sharing');
    ov.style.cssText = 'position:fixed;top:0;right:0;bottom:0;left:0;z-index:100000;background:rgba(19,41,75,0.94);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px;padding:24px;font-family:Montserrat,sans-serif;-webkit-tap-highlight-color:transparent;';
    var img = document.createElement('img');
    img.alt = 'Your Fight for Illinois card';
    if (url) img.src = url;
    img.style.cssText = 'max-width:min(420px,86vw);max-height:56vh;width:auto;height:auto;border-radius:10px;box-shadow:0 18px 50px rgba(0,0,0,0.45);background:#fff;';
    var row = document.createElement('div');
    row.style.cssText = 'display:flex;flex-wrap:wrap;gap:12px;justify-content:center;align-items:center;';
    function mk(label, primary){
      var b = document.createElement('button');
      b.type = 'button';
      b.textContent = label;
      b.style.cssText = 'font-family:Montserrat,sans-serif;font-weight:800;font-size:15px;letter-spacing:0.03em;text-transform:uppercase;border-radius:6px;padding:14px 26px;min-height:48px;cursor:pointer;border:2px solid ' + (primary ? '#fe5f05' : 'rgba(255,255,255,0.7)') + ';background:' + (primary ? '#fe5f05' : 'transparent') + ';color:#fff;';
      return b;
    }
    var shareBtn = mk('Share', true);
    var saveBtn = mk('Save image', false);
    var cancelBtn = document.createElement('button');
    cancelBtn.type = 'button';
    cancelBtn.textContent = 'Cancel';
    cancelBtn.style.cssText = 'font-family:Montserrat,sans-serif;font-weight:700;font-size:14px;background:none;border:0;color:rgba(255,255,255,0.8);text-decoration:underline;padding:10px 14px;min-height:44px;cursor:pointer;';
    function onKey(e){ if (e.key === 'Escape' || e.keyCode === 27) close(); }
    function close(){
      document.removeEventListener('keydown', onKey);
      if (ov.parentNode) ov.parentNode.removeChild(ov);
      if (url) setTimeout(function(){ try { URL.revokeObjectURL(url); } catch (e) {} }, 1500);
    }
    shareBtn.addEventListener('click', function(){ close(); ffiShareNow(blob, opts); });
    saveBtn.addEventListener('click', function(){
      close();
      ffiShareNow(blob, { filename: opts.filename, title: opts.title, fallbackUrl: opts.fallbackUrl, mode: 'download' });
    });
    cancelBtn.addEventListener('click', close);
    ov.addEventListener('click', function(e){ if (e.target === ov) close(); });
    document.addEventListener('keydown', onKey);
    row.appendChild(shareBtn);
    row.appendChild(saveBtn);
    ov.appendChild(img);
    ov.appendChild(row);
    ov.appendChild(cancelBtn);
    document.body.appendChild(ov);
    try { shareBtn.focus(); } catch (e) {}
  }
  function ffiShareNow(blob, opts){
    opts = opts || {};
    var name = opts.filename || 'fight-for-illinois.png';
    var title = opts.title || 'Fight for Illinois';
    var fallbackUrl = opts.fallbackUrl || '';
    var file = null;
    try { file = new File([blob], name, { type: 'image/png' }); } catch (e) {}
    function toast(msg){
      var t = document.createElement('div');
      t.textContent = msg;
      t.setAttribute('role', 'status');
      t.style.cssText = 'position:fixed;left:50%;bottom:28px;transform:translateX(-50%);z-index:99999;background:#13294b;color:#fff;font-family:Montserrat,sans-serif;font-weight:700;font-size:14px;line-height:1.4;padding:12px 18px;border-radius:6px;box-shadow:0 8px 24px rgba(19,41,75,0.35);max-width:min(340px,86vw);text-align:center;';
      document.body.appendChild(t);
      setTimeout(function(){ if (t.parentNode) t.parentNode.removeChild(t); }, 2600);
    }
    function readDataUrl(cb){
      try {
        var fr = new FileReader();
        fr.onload = function(){ cb(String(fr.result)); };
        fr.onerror = function(){ cb(null); };
        fr.readAsDataURL(blob);
      } catch (e) { cb(null); }
    }
    function inAppBrowser(){
      var ua = navigator.userAgent || '';
      return /FBAN|FBAV|Instagram|Line\/|GSA\//i.test(ua) || /; wv\)/.test(ua);
    }
    function openElsewhere(){
      if (fallbackUrl) window.open(fallbackUrl, '_blank', 'noopener');
      else toast('Press and hold the image to save or share it.');
    }
    function download(){
      readDataUrl(function(dataUrl){
        var a = document.createElement('a');
        if (!dataUrl || !('download' in a)) { openElsewhere(); return; }
        a.href = dataUrl;
        a.download = name;
        a.rel = 'noopener';
        document.body.appendChild(a);
        a.click();
        a.remove();
        toast('Saved to your downloads.');
      });
    }
    /* 1. Inside the Fight for Illinois app: the app opens the native share sheet. */
    if (window.FFI_APP && typeof window.FFI_APP.shareImage === 'function') {
      readDataUrl(function(dataUrl){
        if (!dataUrl) { openElsewhere(); return; }
        var p = window.FFI_APP.shareImage(dataUrl, name);
        if (p && p['catch']) p['catch'](function(){});
      });
      return;
    }
    /* 2. Safari or Chrome on a phone: the browser's own share sheet. */
    if (opts.mode === 'download') { download(); return; }
    if (file && navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
      navigator.share({ files: [file], title: title })['catch'](function(err){
        if (!err || err.name !== 'AbortError') download();
      });
      return;
    }
    /* 3. Another app's browser: the standalone page. 4. Desktop: download. */
    if (inAppBrowser()) { openElsewhere(); return; }
    download();
  }
  /* One payload shape for every page. Unknown keys are simply absent. */
  function jsonAttr(btn, k){
    var v = btn.getAttribute('data-share-' + k);
    if (!v) return null;
    try { return JSON.parse(v); } catch (e) { return null; }
  }
  function payload(btn){
    var g = function(k){ return btn.getAttribute('data-share-' + k) || ''; };
    var p = {
      pre: g('pre'), num: g('num'), only: g('only'), label: g('label'),
      rank: g('rank'), rankOf: g('rank-of'), title: g('title'), sub: g('sub'),
      hed: g('hed'), bubble: g('bubble'), contrast: g('contrast'), source: g('source'),
      colhd: jsonAttr(btn, 'colhd'), tbl: jsonAttr(btn, 'tbl'), cols: jsonAttr(btn, 'cols'),
      delta: jsonAttr(btn, 'delta'), bars: jsonAttr(btn, 'bars'), rows: jsonAttr(btn, 'rows'),
      pie: jsonAttr(btn, 'pie')
    };
    if (btn.getAttribute('data-share-valorange')) p.val_orange = true;
    if (btn.getAttribute('data-share-subbig')) p.sub_big = true;
    if (typeof window.FFI_SHARE_RESOLVE === 'function') { p = window.FFI_SHARE_RESOLVE(btn, p) || p; }
    return p;
  }
  /* A payload with nothing in it (a button whose data is filled in later, and
     was tapped before that happened) must not produce a logo-only card. */
  function hasContent(o){
    return !!(o.num || o.title || o.hed || o.label ||
      (o.rows && o.rows.length) || (o.tbl && o.tbl.length) || (o.bars && o.bars.length) ||
      (o.cols && o.cols.length) || (o.delta && o.delta.length) || (o.pie && o.pie.length));
  }
  function draw(o, cb){
    if (!hasContent(o)) { cb(null); return; }
    if (o.pie && o.pie.length) { draw_pie(o, cb); return; }
    if (o.cols && o.cols.length) { drawCols(o, cb); return; }
    if (o.delta && o.delta.length) { drawDelta(o, cb); return; }
    if (o.bars && o.bars.length) { drawBars(o, cb); return; }
    if (o.tbl && o.tbl.length) { drawTbl(o, cb); return; }
    if (o.rows && o.rows.length) { drawRows(o, cb); return; }
    drawNum(o, cb);
  }
  /* One delegated listener on the document, bubble phase. No per-button
     wiring and no attribute writes: setting attributes on nodes the page
     framework owns makes it re-render, which re-wires, which re-renders -
     buttons that appear later (search results, district pickers) are picked
     up here for free. */
  var busy = false;
  function onTap(ev){
    var el = ev.target;
    while (el && el.nodeType === 1) {
      var c = el.className ? String(el.className) : '';
      if (c.indexOf('ffi-share') > -1) break;
      el = el.parentNode;
    }
    if (!el || el.nodeType !== 1) return;
    if (ev.preventDefault) ev.preventDefault();
    if (busy) return;
    busy = true;
    var btn = el;
    var name = btn.getAttribute('data-share-filename') || window.FFI_SHARE_FILENAME || 'fight-for-illinois.png';
    draw(payload(btn), function(blob){
      busy = false;
      if (!blob) return;
      ffiShareCard(blob, { filename: name, title: 'Fight for Illinois' });
    });
  }
  function wire(){ /* nothing to wire: the delegated listener covers every button */ }
  document.addEventListener('click', onTap, false);
  window.FFI_SHARE_SCAN = wire;
  window.FFI_makeCard = draw;
  window.ffiShareCard = ffiShareCard;
  window.FFI_CARDS = { draw: draw, show: ffiShareCard, shareNow: ffiShareNow, payload: payload, wire: wire };
})();

